### ISSUE TITLE
Install Linuxbrew on Alpine WSL 

### ISSUE THREAD

**Issue by amryadam** [Homebrew/linuxbrew-core#13467]
- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

## What you were trying to do (and why)
I was trying to install Linuxbrew on Alpine WSL windows v1903, but i get error during installation , i tried to troubleshoot but no success
___
## What happened (include command output)
``` 

sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"

==> This script will install:
/home/amr/.linuxbrew/bin/brew
/home/amr/.linuxbrew/share/doc/homebrew
/home/amr/.linuxbrew/share/man/man1/brew.1
/home/amr/.linuxbrew/share/zsh/site-functions/_brew
/home/amr/.linuxbrew/etc/bash_completion.d/brew
/home/amr/.cache/Homebrew/
/home/amr/.linuxbrew/Homebrew
==> The following new directories will be created:
/home/amr/.linuxbrew/bin
/home/amr/.linuxbrew/etc
/home/amr/.linuxbrew/include
/home/amr/.linuxbrew/lib
/home/amr/.linuxbrew/sbin
/home/amr/.linuxbrew/share
/home/amr/.linuxbrew/var
/home/amr/.linuxbrew/opt
/home/amr/.linuxbrew/share/zsh
/home/amr/.linuxbrew/share/zsh/site-functions
/home/amr/.linuxbrew/Cellar
/home/amr/.linuxbrew/Caskroom
/home/amr/.linuxbrew/Homebrew
/home/amr/.linuxbrew/Frameworks

Press RETURN to continue or any other key to abort
==> /bin/mkdir -p /home/amr/.linuxbrew
==> /bin/chown amr:amr /home/amr/.linuxbrew
==> /bin/mkdir -p /home/amr/.linuxbrew/bin /home/amr/.linuxbrew/etc /home/amr/.linuxbrew/include /home/amr/.linuxbrew/lib /home/amr/.linuxbrew/sbin /home/amr/.linuxbrew/share /home/amr/.linuxbrew/var /home/amr/.linuxbrew/opt /home/amr/.linuxbrew/share/zsh /home/amr/.linuxbrew/share/zsh/site-functions /home/amr/.linuxbrew/Cellar /home/amr/.linuxbrew/Caskroom /home/amr/.linuxbrew/Homebrew /home/amr/.linuxbrew/Frameworks
==> /bin/chmod g+rwx /home/amr/.linuxbrew/bin /home/amr/.linuxbrew/etc /home/amr/.linuxbrew/include /home/amr/.linuxbrew/lib /home/amr/.linuxbrew/sbin /home/amr/.linuxbrew/share /home/amr/.linuxbrew/var /home/amr/.linuxbrew/opt /home/amr/.linuxbrew/share/zsh /home/amr/.linuxbrew/share/zsh/site-functions /home/amr/.linuxbrew/Cellar /home/amr/.linuxbrew/Caskroom /home/amr/.linuxbrew/Homebrew /home/amr/.linuxbrew/Frameworks
==> /bin/chmod 755 /home/amr/.linuxbrew/share/zsh /home/amr/.linuxbrew/share/zsh/site-functions
==> /bin/chown amr /home/amr/.linuxbrew/bin /home/amr/.linuxbrew/etc /home/amr/.linuxbrew/include /home/amr/.linuxbrew/lib /home/amr/.linuxbrew/sbin /home/amr/.linuxbrew/share /home/amr/.linuxbrew/var /home/amr/.linuxbrew/opt /home/amr/.linuxbrew/share/zsh /home/amr/.linuxbrew/share/zsh/site-functions /home/amr/.linuxbrew/Cellar /home/amr/.linuxbrew/Caskroom /home/amr/.linuxbrew/Homebrew /home/amr/.linuxbrew/Frameworks
==> /bin/chgrp amr /home/amr/.linuxbrew/bin /home/amr/.linuxbrew/etc /home/amr/.linuxbrew/include /home/amr/.linuxbrew/lib /home/amr/.linuxbrew/sbin /home/amr/.linuxbrew/share /home/amr/.linuxbrew/var /home/amr/.linuxbrew/opt /home/amr/.linuxbrew/share/zsh /home/amr/.linuxbrew/share/zsh/site-functions /home/amr/.linuxbrew/Cellar /home/amr/.linuxbrew/Caskroom /home/amr/.linuxbrew/Homebrew /home/amr/.linuxbrew/Frameworks
==> /bin/mkdir -p /home/amr/.cache/Homebrew
==> Downloading and installing Linuxbrew...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 123998 (delta 0), reused 5 (delta 0), pack-reused 123990
Receiving objects: 100% (123998/123998), 29.31 MiB | 543.00 KiB/s, done.
Resolving deltas: 100% (90854/90854), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
 * [new tag]         0.1        -> 0.1
 * [new tag]         0.2        -> 0.2
 * [new tag]         0.3        -> 0.3
 * [new tag]         0.4        -> 0.4
 * [new tag]         0.5        -> 0.5
 * [new tag]         0.6        -> 0.6
 * [new tag]         0.7        -> 0.7
 * [new tag]         0.7.1      -> 0.7.1
 * [new tag]         0.8        -> 0.8
 * [new tag]         0.8.1      -> 0.8.1
 * [new tag]         0.9        -> 0.9
 * [new tag]         0.9.1      -> 0.9.1
 * [new tag]         0.9.2      -> 0.9.2
 * [new tag]         0.9.3      -> 0.9.3
 * [new tag]         0.9.4      -> 0.9.4
 * [new tag]         0.9.5      -> 0.9.5
 * [new tag]         0.9.8      -> 0.9.8
 * [new tag]         0.9.9      -> 0.9.9
 * [new tag]         1.0.0      -> 1.0.0
 * [new tag]         1.0.1      -> 1.0.1
 * [new tag]         1.0.2      -> 1.0.2
 * [new tag]         1.0.3      -> 1.0.3
 * [new tag]         1.0.4      -> 1.0.4
 * [new tag]         1.0.5      -> 1.0.5
 * [new tag]         1.0.6      -> 1.0.6
 * [new tag]         1.0.7      -> 1.0.7
 * [new tag]         1.0.8      -> 1.0.8
 * [new tag]         1.0.9      -> 1.0.9
 * [new tag]         1.1.0      -> 1.1.0
 * [new tag]         1.1.1      -> 1.1.1
 * [new tag]         1.1.10     -> 1.1.10
 * [new tag]         1.1.11     -> 1.1.11
 * [new tag]         1.1.12     -> 1.1.12
 * [new tag]         1.1.13     -> 1.1.13
 * [new tag]         1.1.2      -> 1.1.2
 * [new tag]         1.1.3      -> 1.1.3
 * [new tag]         1.1.4      -> 1.1.4
 * [new tag]         1.1.5      -> 1.1.5
 * [new tag]         1.1.6      -> 1.1.6
 * [new tag]         1.1.7      -> 1.1.7
 * [new tag]         1.1.8      -> 1.1.8
 * [new tag]         1.1.9      -> 1.1.9
 * [new tag]         1.2.0      -> 1.2.0
 * [new tag]         1.2.1      -> 1.2.1
 * [new tag]         1.2.2      -> 1.2.2
 * [new tag]         1.2.3      -> 1.2.3
 * [new tag]         1.2.4      -> 1.2.4
 * [new tag]         1.2.5      -> 1.2.5
 * [new tag]         1.2.6      -> 1.2.6
 * [new tag]         1.3.0      -> 1.3.0
 * [new tag]         1.3.1      -> 1.3.1
 * [new tag]         1.3.2      -> 1.3.2
 * [new tag]         1.3.3      -> 1.3.3
 * [new tag]         1.3.4      -> 1.3.4
 * [new tag]         1.3.5      -> 1.3.5
 * [new tag]         1.3.6      -> 1.3.6
 * [new tag]         1.3.7      -> 1.3.7
 * [new tag]         1.3.8      -> 1.3.8
 * [new tag]         1.3.9      -> 1.3.9
 * [new tag]         1.4.0      -> 1.4.0
 * [new tag]         1.4.1      -> 1.4.1
 * [new tag]         1.4.2      -> 1.4.2
 * [new tag]         1.4.3      -> 1.4.3
 * [new tag]         1.5.0      -> 1.5.0
 * [new tag]         1.5.1      -> 1.5.1
 * [new tag]         1.5.10     -> 1.5.10
 * [new tag]         1.5.11     -> 1.5.11
 * [new tag]         1.5.12     -> 1.5.12
 * [new tag]         1.5.13     -> 1.5.13
 * [new tag]         1.5.14     -> 1.5.14
 * [new tag]         1.5.2      -> 1.5.2
 * [new tag]         1.5.3      -> 1.5.3
 * [new tag]         1.5.4      -> 1.5.4
 * [new tag]         1.5.5      -> 1.5.5
 * [new tag]         1.5.6      -> 1.5.6
 * [new tag]         1.5.7      -> 1.5.7
 * [new tag]         1.5.8      -> 1.5.8
 * [new tag]         1.5.9      -> 1.5.9
 * [new tag]         1.6.0      -> 1.6.0
 * [new tag]         1.6.1      -> 1.6.1
 * [new tag]         1.6.10     -> 1.6.10
 * [new tag]         1.6.11     -> 1.6.11
 * [new tag]         1.6.12     -> 1.6.12
 * [new tag]         1.6.13     -> 1.6.13
 * [new tag]         1.6.14     -> 1.6.14
 * [new tag]         1.6.15     -> 1.6.15
 * [new tag]         1.6.16     -> 1.6.16
 * [new tag]         1.6.17     -> 1.6.17
 * [new tag]         1.6.2      -> 1.6.2
 * [new tag]         1.6.3      -> 1.6.3
 * [new tag]         1.6.4      -> 1.6.4
 * [new tag]         1.6.5      -> 1.6.5
 * [new tag]         1.6.6      -> 1.6.6
 * [new tag]         1.6.7      -> 1.6.7
 * [new tag]         1.6.8      -> 1.6.8
 * [new tag]         1.6.9      -> 1.6.9
 * [new tag]         1.7.0      -> 1.7.0
 * [new tag]         1.7.1      -> 1.7.1
 * [new tag]         1.7.2      -> 1.7.2
 * [new tag]         1.7.3      -> 1.7.3
 * [new tag]         1.7.4      -> 1.7.4
 * [new tag]         1.7.5      -> 1.7.5
 * [new tag]         1.7.6      -> 1.7.6
 * [new tag]         1.7.7      -> 1.7.7
 * [new tag]         1.8.0      -> 1.8.0
 * [new tag]         1.8.1      -> 1.8.1
 * [new tag]         1.8.2      -> 1.8.2
 * [new tag]         1.8.3      -> 1.8.3
 * [new tag]         1.8.4      -> 1.8.4
 * [new tag]         1.8.5      -> 1.8.5
 * [new tag]         1.8.6      -> 1.8.6
 * [new tag]         1.9.0      -> 1.9.0
 * [new tag]         1.9.1      -> 1.9.1
 * [new tag]         1.9.2      -> 1.9.2
 * [new tag]         1.9.3      -> 1.9.3
 * [new tag]         2.0.0      -> 2.0.0
 * [new tag]         2.0.1      -> 2.0.1
 * [new tag]         2.0.2      -> 2.0.2
 * [new tag]         2.0.3      -> 2.0.3
 * [new tag]         2.0.4      -> 2.0.4
 * [new tag]         2.0.5      -> 2.0.5
 * [new tag]         2.0.6      -> 2.0.6
 * [new tag]         2.1.0      -> 2.1.0
 * [new tag]         2.1.1      -> 2.1.1
 * [new tag]         2.1.2      -> 2.1.2
 * [new tag]         2.1.3      -> 2.1.3
 * [new tag]         2.1.4      -> 2.1.4
Checking out files: 100% (1796/1796), done.
HEAD is now at 7bcd70b29 Merge pull request #6202 from Homebrew/imgbot
sort: unrecognized option: field-separator=.
grep: unrecognized option: max-count=1
BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.

Usage: sort [-nrugMcszbdfiokt] [-o FILE] [-k start[.offset][opts][,end[.offset][opts]] [-t CHAR] [FILE]...

Sort lines of text

        -o FILE Output to FILE
        -c      Check whether input is sorted
        -b      Ignore leading blanks
        -f      Ignore case
        -i      Ignore unprintable characters
        -d      Dictionary order (blank or alphanumeric only)
        -n      Sort numbers
        -g      General numerical sort
        -M      Sort month
        -t CHAR Field separator
        -k N[,M] Sort by Nth field
        -r      Reverse sort order
        -s      Stable (don't sort ties alphabetically)
        -u      Suppress duplicate lines
        -z      Lines are terminated by NUL, not newlineBusyBox v1.29.3 (2019-01-24 07:45:07 UTC)
 multi-call binary.

Usage: grep [-HhnlLoqvsriwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...

Search for PATTERN in FILEs (or stdin)

        -H      Add 'filename:' prefix
        -h      Do not add 'filename:' prefix
        -n      Add 'line_no:' prefix
        -l      Show only names of files that match
        -L      Show only names of files that don't match
        -c      Show only count of matching lines
        -o      Show only the matching part of line
        -q      Quiet. Return 0 if PATTERN is found, 1 otherwise
        -v      Select non-matching lines
        -s      Suppress open and read errors
        -r      Recurse
        -i      Ignore case
        -w      Match whole words only
        -x      Match whole lines only
        -F      PATTERN is a literal (not regexp)
        -E      PATTERN is an extended regexp
        -m N    Match up to N times per file
        -A N    Print N lines of trailing context
        -B N    Print N lines of leading context
        -C N    Same as '-A N -B N'
        -e PTRN Pattern to match
        -f FILE Read pattern from file
Traceback (most recent call last):
        11: from /home/amr/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
        10: from /home/amr/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
         9: from /home/amr/.linuxbrew/Homebrew/Library/Homebrew/global.rb:13:in `<top (required)>'
         8: from /home/amr/.linuxbrew/Homebrew/Library/Homebrew/global.rb:13:in `require'
         7: from /home/amr/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/numeric/time.rb:3:in `<top (required)>'
         6: from /home/amr/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/numeric/time.rb:3:in `require'
         5: from /home/amr/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/duration.rb:3:in `<top (required)>'
         4: from /home/amr/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/duration.rb:3:in `require'
         3: from /home/amr/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
         2: from /home/amr/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/array/conversions.rb:3:in `require'
         1: from /home/amr/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/xml_mini.rb:5:in `<top (required)>'
/home/amr/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/xml_mini.rb:5:in `require': cannot load such file -- bigdecimal (LoadError)
Failed during: /home/amr/.linuxbrew/bin/brew update --force
```
## What you expected to happen
Install Linuxbrew \^_^
___
## Step-by-step reproduction instructions (by running `brew install` commands)
i used [Install Linuxbrew on Alpine Linux
 ](https://github.com/Linuxbrew/brew/wiki/Alpine-Linux)
```
su
apk update
apk add bash build-base curl file git gzip libc6-compat ncurses ruby ruby-dbm ruby-etc ruby-irb ruby-json sudo
adduser -D -s /bin/bash linuxbrew
echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers
su -l linuxbrew
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"

```
Then the error will accure

**Comment by jonchang** [comment]
It looks like your copy of `sort` and `grep` do not support long arguments. We might look into a pull request that changes this behavior if you submit it to Homebrew/brew.
