### ISSUE TITLE
bazel: build failure on Debian 9

### ISSUE THREAD

**Issue by fcying** [Homebrew/linuxbrew-core#13619]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/fcying/bed35e8da016a8cae77896d54d1041d7
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
```
brew install bazel
```

- What happened (include command output)
```
$ brew install bazel
==> Installing bazel
==> Downloading https://github.com/bazelbuild/bazel/releases/download/0.26.1/bazel-0.26.1-dist.zip
Already downloaded: /home/fcying/.cache/Homebrew/downloads/120c0f78ad757e168d4f6fd43801ab63c75ca69d06aa20f076e234c5fdaf553b--bazel-0.26.1-dist.zip
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis failed
INFO: Elapsed time: 22.094s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (211 packages loaded, 10078 target\
s configured)

ERROR: Could not build Bazel

READ THIS: https://docs.brew.sh/Troubleshooting
```

**Comment by ekremkaraca** [comment]
I had similar issue on Debian 10. Here's the output which might be helpful for us:

```shell
...
^M^MAnalyzing: target //src:bazel_nojdk (215 packages loaded, 10529 targets config\
ured)
^M^MINFO: Analyzed target //src:bazel_nojdk (215 packages loaded, 10529 targets configured).
Building: checking cached actions
^MINFO: Found 1 target...
Building: checking cached actions
^M[0 / 8] [Prepa] BazelWorkspaceStatusAction stable-status.txt
^MERROR: /tmp/bazel-20190713-21211-1ygf2tk/sources/third_party/ijar/BUILD:81:1: C++ compilation of rule '//third_party/ijar:ijar' failed (Exit 1): gcc-8 failed: error executing command 
  (cd /tmp/bazel_LhnAtv9M/out/execroot/io_bazel && \
  exec env - \
    PATH=/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super:/home/linuxbrew/.linuxbrew/opt/python/bin:/home/linuxbrew/.linuxbrew/opt/openjdk/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    PWD=/proc/self/cwd \
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-8 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/third_party/ijar/_objs/ijar/ijar.d '-frandom-seed=bazel-out/host/bin/third_party/ijar/_objs/ijar/ijar.o' -DBLAZE_OPENSOURCE -iquote . -iquote bazel-out/host/bin -iquote external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -isystem third_party/zlib -isystem bazel-out/host/bin/third_party/zlib -g0 -g0 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c third_party/ijar/ijar.cc -o bazel-out/host/bin/third_party/ijar/_objs/ijar/ijar.o)
Execution platform: //:default_host_platform
[7 / 23] 3 actions, 2 running
    [Scann] Compiling src/main/cpp/util/file_posix.cc [for host] ...
^M^Mgcc-8: The build tool has reset ENV; --env=std required.
[9 / 23] [Scann] Compiling src/main/cpp/util/file_posix.cc [for host]
^MTarget //src:bazel_nojdk failed to build
[11 / 23] checking cached actions
^MINFO: Elapsed time: 52.043s, Critical Path: 0.04s
[11 / 23] checking cached actions
^MINFO: 0 processes.
[11 / 23] checking cached actions
^MFAILED: Build did NOT complete successfully
^MFAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
...
```

**Comment by thoughton** [comment]
Same here on Ubuntu 19.04.

**Comment by Liu-Richard** [comment]
any good ideas?
I had similar issue on Debian 10. Here's the output:
Note: Recompile with -Xlint:deprecation for details.
1 warning
ERROR: /home/liuzhigang/Bazel/bazel-0.27.0/bazel-0.27.0/src/BUILD:25:2: Executing genrule //src:install_base_key-file_nojdk failed (Exit 2): bash failed: error executing command
  (cd /tmp/bazel_sYCOcgO1/out/execroot/io_bazel && \
  exec env - \
    PATH=/opt/tools/installed/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; set -e -o pipefail && cat bazel-out/aarch64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar bazel-out/aarch64-opt/bin/src/main/cpp/client bazel-out/aarch64-opt/bin/src/main/native/libunix.so bazel-out/aarch64-opt/bin/src/main/tools/build-runfiles bazel-out/aarch64-opt/bin/src/main/tools/process-wrapper bazel-out/aarch64-opt/bin/src/main/tools/linux-sandbox bazel-out/aarch64-opt/bin/tools/osx/xcode-locator bazel-out/aarch64-opt/bin/src/embedded_tools_nojdk.zip | sort | md5sum | awk '\''{ print $1; }'\'' > bazel-out/aarch64-opt/bin/src/install_base_key_nojdk')
Execution platform: @bazel_tools//platforms:host_platform
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 648.673s, Critical Path: 117.91s
INFO: 1744 processes: 1508 local, 236 worker.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel

**Comment by jpopadak** [comment]
Same issue here.

_Windows 10 Pro
Version 2004
OS Build 19037.1_

```
┌─[jpopadak@DESKTOP-JPOP] - [/mnt/c/Users/Jim] - [Sat Dec 07, 23:07]
└─[$] <> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

```
┌─[jpopadak@DESKTOP-JPOP] - [/mnt/c/Users/Jim] - [Sat Dec 07, 22:54]
└─[$] <> brew install bazel --debug
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxb    rew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bazel.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxb    rew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/adoptopenjdk.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxb    rew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxb    rew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxb    rew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxb    rew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxb    rew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxb    rew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ncurses.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxb    rew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gpatch.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxb    rew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxb    rew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxb    rew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxb    rew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bzip2.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxb    rew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libffi.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /home/linuxbrew/.linu    xbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bazel.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/adoptopenjdk.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ncurses.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gpatch.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bzip2.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libffi.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/binutils.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linux    brew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/make.rb
==> Downloading https://github.com/bazelbuild/bazel/releases/download/1.2.1/bazel-1.2.1-dist.zip
/usr/bin/curl -q --globoff --show-error --user-agent Linuxbrew/2.2.0\ \(Linux\;\ x86_64\ Ubuntu\ 18.04.1\ LTS\)\ curl/7.    58.0 --location --silent --head --request GET https://github.com/bazelbuild/bazel/releases/download/1.2.1/bazel-1.2.1-di    st.zip
Already downloaded: /home/jpopadak/.cache/Homebrew/downloads/84b900e4c24bc2df398c131dff7108cde56a24e4479eceb4c9f378a1e8a    adc2b--bazel-1.2.1-dist.zip
unzip -qq -o /home/jpopadak/.cache/Homebrew/downloads/84b900e4c24bc2df398c131dff7108cde56a24e4479eceb4c9f378a1e8aadc2b--    bazel-1.2.1-dist.zip -d /tmp/d20191207-782-1qzzgi0
cp -pR /tmp/d20191207-782-1qzzgi0/.bazelci/. /tmp/bazel-20191207-782-1m77kbw/.bazelci
cp -pR /tmp/d20191207-782-1qzzgi0/.bazelrc /tmp/bazel-20191207-782-1m77kbw/.bazelrc
cp -pR /tmp/d20191207-782-1qzzgi0/AUTHORS /tmp/bazel-20191207-782-1m77kbw/AUTHORS
cp -pR /tmp/d20191207-782-1qzzgi0/BUILD /tmp/bazel-20191207-782-1m77kbw/BUILD
cp -pR /tmp/d20191207-782-1qzzgi0/CHANGELOG.md /tmp/bazel-20191207-782-1m77kbw/CHANGELOG.md
cp -pR /tmp/d20191207-782-1qzzgi0/CODEOWNERS /tmp/bazel-20191207-782-1m77kbw/CODEOWNERS
cp -pR /tmp/d20191207-782-1qzzgi0/CONTRIBUTING.md /tmp/bazel-20191207-782-1m77kbw/CONTRIBUTING.md
cp -pR /tmp/d20191207-782-1qzzgi0/CONTRIBUTORS /tmp/bazel-20191207-782-1m77kbw/CONTRIBUTORS
cp -pR /tmp/d20191207-782-1qzzgi0/ISSUE_TEMPLATE.md /tmp/bazel-20191207-782-1m77kbw/ISSUE_TEMPLATE.md
cp -pR /tmp/d20191207-782-1qzzgi0/LICENSE /tmp/bazel-20191207-782-1m77kbw/LICENSE
cp -pR /tmp/d20191207-782-1qzzgi0/README.md /tmp/bazel-20191207-782-1m77kbw/README.md
cp -pR /tmp/d20191207-782-1qzzgi0/WORKSPACE /tmp/bazel-20191207-782-1m77kbw/WORKSPACE
cp -pR /tmp/d20191207-782-1qzzgi0/combine_distfiles.py /tmp/bazel-20191207-782-1m77kbw/combine_distfiles.py
cp -pR /tmp/d20191207-782-1qzzgi0/combine_distfiles_to_tar.sh /tmp/bazel-20191207-782-1m77kbw/combine_distfiles_to_tar.sh   cp -pR /tmp/d20191207-782-1qzzgi0/compile.sh /tmp/bazel-20191207-782-1m77kbw/compile.sh
cp -pR /tmp/d20191207-782-1qzzgi0/derived/. /tmp/bazel-20191207-782-1m77kbw/derived
cp -pR /tmp/d20191207-782-1qzzgi0/distdir.bzl /tmp/bazel-20191207-782-1m77kbw/distdir.bzl
cp -pR /tmp/d20191207-782-1qzzgi0/examples/. /tmp/bazel-20191207-782-1m77kbw/examples
cp -pR /tmp/d20191207-782-1qzzgi0/platforms/. /tmp/bazel-20191207-782-1m77kbw/platforms
Target //src:bazel_nojdk failed to build
ERROR: /tmp/bazel-20191207-782-1m77kbw/sources/src/main/protobuf/BUILD:150:1 C++ compilation of rule '//third_party/protobuf/3.6.1:protobuf' failed (Exit 1)
INFO: Elapsed time: 64.128s, Critical Path: 0.35s
INFO: 6 processes: 6 local.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
/usr/bin/curl --version
java -version
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:13:in `raise'
FormulaUnavailableError: No available formula with the name "xorg"
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:13:in `raise'
BuildError: Failed executing: ./compile.sh
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
==> Kept temporary files
Temporary files retained at /tmp/bazel-20191207-782-1m77kbw

READ THIS: https://docs.brew.sh/Troubleshooting

/usr/bin/curl -q --globoff --show-error --user-agent Linuxbrew/2.2.0\ \(Linux\;\ x86_64\ Ubuntu\ 18.04.1\ LTS\)\ curl/7.58.0 --location https://api.github.com/search/issues\?q=bazel\+state\%3Aopen\+repo\%3AHomebrew\%2Flinuxbrew-core\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --dump-header /tmp/github_api_headers20191207-115-1r9k3fx
These open issues may also help:
bazel: build failure on Debian 9 https://github.com/Homebrew/linuxbrew-core/issues/13619
bazel: build failure with JAVA_HOME not set https://github.com/Homebrew/linuxbrew-core/issues/14087
```

**Comment by thoughton** [comment]
Don't think this is actually stale.

**Comment by dawidd6** [comment]
Well, it kinda is, cause we can't fix it since a long time.
