### ISSUE TITLE
snapcraft: error during installation

### ISSUE THREAD

**Issue by dawidd6** [Homebrew/linuxbrew-core#14107]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I was trying to install `snapcraft` package via `brew` in official Docker `linuxbrew/brew` image.

1. Pull `linuxbrew/brew` Docker image and run it.
2. Execute `brew install snapcraft`
3. Observe getting this output and error at the end:
```
root@fde41254f50b:/home/linuxbrew# brew install snapcraft
==> Downloading https://files.pythonhosted.org/packages/ff/9c/07776f4f192a3bb454221ef00cc865fbbbd5d5285d134b36b6aa1890d91d/snapcraft-3.3.tar.gz
Already downloaded: /root/.cache/Homebrew/downloads/287800da8f61ad73d39d0e079ce88b0dc2a54ef548c7344acfd963fa60db224d--snapcraft-3.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/37/27/706af3ee62032933a3217454609c50a5325a6bd9c2c2f495b58c456ba286/virtualenv-16.6.1.tar.gz
Already downloaded: /root/.cache/Homebrew/downloads/3c930834dac51edb05b7f34f88664cf348741680c6b1d860dc7ddc084d5b17eb--virtualenv-16.6.1.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/snapcraft--homebrew-virtualenv-20190704-30398-k2kz5o/target --install-scripts=/tmp/snapcraft--ho
==> python3 -s /tmp/snapcraft--homebrew-virtualenv-20190704-30398-k2kz5o/target/bin/virtualenv -p python3 /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec
==> Downloading https://files.pythonhosted.org/packages/15/d4/2f888fc463d516ff7bf2379a4e9a552fef7f22a94147655d9b1097108248/certifi-2018.1.18.tar.gz
Already downloaded: /root/.cache/Homebrew/downloads/70a3328b3bef7ddb73f01e9ddbe220926f47db5433fef0afbda5f5b776abd9a9--certifi-2018.1.18.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/snapcraft--certifi-20190704-30398-tbf
==> Downloading https://files.pythonhosted.org/packages/10/f7/3b302ff34045f25065091d40e074479d6893882faef135c96f181a57ed06/cffi-1.11.4.tar.gz
Already downloaded: /root/.cache/Homebrew/downloads/3d53a7cdf7a28834246876483f8b6dd34efcc79e2a91ba99c88eb4db7216318d--cffi-1.11.4.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/snapcraft--cffi-20190704-30398-18fv6x
Last 15 lines from /root/.cache/Homebrew/Logs/snapcraft/04.pip:
Removed build tracker '/tmp/pip-req-tracker-ki32ooj0'
ERROR: Command "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-ixryuuh2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zo8saavf/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/include/site/python3.7/cffi" failed with error code 1 in /tmp/pip-req-build-ixryuuh2/
Exception information:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 951, in install
    spinner=spinner,
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-ixryuuh2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zo8saavf/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/include/site/python3.7/cffi" failed with error code 1 in /tmp/pip-req-build-ixryuuh2/

READ THIS: https://docs.brew.sh/Troubleshooting
```

---

```
root@fde41254f50b:/home/linuxbrew# brew config             
HOMEBREW_VERSION: 2.1.6-44-g895467a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 895467ad9f57a9245c36def26abca729f2559fbb
Last commit: 29 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 86502d381a32704b36a8bc09ee1dbdb983b0f913
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /root/.cache/Homebrew
HOMEBREW_LOGS: /root/.cache/Homebrew/Logs
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.22.0 => /usr/bin/git
Curl: 7.47.0 => /usr/bin/curl
Kernel: Linux 4.15.0-52-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.6 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: N/A
xorg: N/A
```

```
root@fde41254f50b:/home/linuxbrew# brew doctor
Your system is ready to brew.
```

**Comment by iMichka** [comment]
I am going to close this. We have been working on this periodically since July, without much success. Anybody can open a new PR with a  fix. Looks like packaging snap craft is quite hard ...
