### ISSUE TITLE
Torch and opencv cannot find shared libraries on Redhat 7.6

### ISSUE THREAD

**Issue by Albert65** [Homebrew/linuxbrew-core#14751]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [*] ran `brew update` and can still reproduce the problem?
- [*] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Installing brew, opencv and torch on Redhat 7.6/64.

- What happened (include command output)

Inside python3 prompt:
```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.4/lib/python3.7/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory

>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.4/lib/python3.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory
```

- What you expected to happen

Import without issues. In my case libSM.so.6 exists in /usr/lib64, libstdc++.so.6 in /usr/lib64 (system version) and in /home/linuxbrew/.linuxbrew/lib. I also tried to play with LD_LIBRARY_PATH and LD_LIBRARY_PATH_64 - no luck.

- Step-by-step reproduction instructions (by running `brew install` commands)

I installed Linuxbrew following the instructions.
Then installed Opencv for C++ development was installed:
```
brew install python3 opencv
```
along with some python packages and again (!) opencv:
```
pip3 install pytz
pip3 install setuptools wheel numpy scipy Pillow matplotlib pandas cython psutil sympy scikit-learn scikit-image opencv-python opencv-contrib-python torch torchvision ipython jupyter joblib statsmodels retrying solartime workalendar
```

**Comment by Albert65** [comment]
One addition. If I import sklearn before torch everything is fine:
```
import sklearn
import torch
```
I am wondering what happens with library path resolution.
