### ISSUE TITLE
brew install certbot fails on Amazon Linux 2

### ISSUE THREAD

**Issue by aruld** [Homebrew/linuxbrew-core#14892]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/aruld/efafec77d43a297a5f7e4df8a274e04d
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
Trying to install certbot on Amazon Linux 2
- What happened (include command output)
```
brew install certbot
==> Downloading https://github.com/certbot/certbot/archive/v0.37.1.tar.gz
Already downloaded: /home/ec2-user/.cache/Homebrew/downloads/18c3e083e28cb64de1658ce90ae18852a90f7cc3388f31bdc7ab5a0d413933ad--certbot-0.37.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/a9/8a/580c7176f01540615c2eb3f3ab5462613b4beac4aa63410be89ecc7b7472/virtualenv-16.7.2.tar.gz
Already downloaded: /home/ec2-user/.cache/Homebrew/downloads/93188db770e5a2cc745d843c379ae7f650e2198f127a55a5aa3758689f60b5c4--virtualenv-16.7.2.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/certbot--homebrew-virtualenv-20190817-5609-g6ti05/target --install-scripts=/tmp/
==> python3 -s /tmp/certbot--homebrew-virtualenv-20190817-5609-g6ti05/target/bin/virtualenv -p python3 /home/linuxbrew/.linuxbrew/Cellar/certbot/0.37.1/
==> Downloading https://files.pythonhosted.org/packages/fc/f1/8db7daa71f414ddabfa056c4ef792e1461ff655c2ae2928a2b675bfed6b4/asn1crypto-0.24.0.tar.gz
Already downloaded: /home/ec2-user/.cache/Homebrew/downloads/4be04f2e7c7591dc271e1a4566ed931b221fbf07ec8ca29ba7fc4540e505f7ec--asn1crypto-0.24.0.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/certbot/0.37.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/certbot--asn1crypto-
==> Downloading https://files.pythonhosted.org/packages/c5/67/5d0548226bcc34468e23a0333978f0e23d28d0b3f0c71a151aef9c3f7680/certifi-2019.6.16.tar.gz
Already downloaded: /home/ec2-user/.cache/Homebrew/downloads/3a3ef674b22ba80ddd7cb939f8db2c1c09339ab456b2a270a63611c8281d67c8--certifi-2019.6.16.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/certbot/0.37.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/certbot--certifi-201
==> Downloading https://files.pythonhosted.org/packages/93/1a/ab8c62b5838722f29f3daffcc8d4bd61844aa9b5f437341cc890ceee483b/cffi-1.12.3.tar.gz
Already downloaded: /home/ec2-user/.cache/Homebrew/downloads/8d0e9e3bcf799c6b77d8557a456dce2288eb30a151947814c78e268b78bba2f5--cffi-1.12.3.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/certbot/0.37.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/certbot--cffi-201908
Last 15 lines from /home/ec2-user/.cache/Homebrew/Logs/certbot/05.pip:
Removed build tracker '/tmp/pip-req-tracker-l_jmkurb'
ERROR: Command errored out with exit status 1: /home/linuxbrew/.linuxbrew/Cellar/certbot/0.37.1/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-p6w8ovw7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-p6w8ovw7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-35fwzbp4/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/certbot/0.37.1/libexec/include/site/python3.7/cffi Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/certbot/0.37.1/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/certbot/0.37.1/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "/home/linuxbrew/.linuxbrew/Cellar/certbot/0.37.1/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/home/linuxbrew/.linuxbrew/Cellar/certbot/0.37.1/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 959, in install
    spinner=spinner,
  File "/home/linuxbrew/.linuxbrew/Cellar/certbot/0.37.1/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 931, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/linuxbrew/.linuxbrew/Cellar/certbot/0.37.1/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-p6w8ovw7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-p6w8ovw7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-35fwzbp4/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/certbot/0.37.1/libexec/include/site/python3.7/cffi Check the logs for full command output.
```
- What you expected to happen
successful installation of certbot
- Step-by-step reproduction instructions (by running `brew install` commands)
Run ```brew install certbot``` on Amazon Linux 2

**Comment by issyl0** [comment]
Hi, @aruld. Sorry you're having problems installing Homebrew packages on Amazon Linux 2. Thanks for raising this issue.

Have you installed the [pre-requisite packages](https://docs.brew.sh/Homebrew-on-Linux#fedora-centos-or-red-hat)? If you run the following, are you then able to install `certbot`?

```
sudo yum groupinstall 'Development Tools'
sudo yum install curl file git
```

**Comment by aruld** [comment]
@issyl0 Yes, I did install those right after installing brew.

**Comment by aruld** [comment]
@issyl0 Here is the [install log](https://gist.github.com/aruld/ca68ac0547dfa82249deab89ba022b4d)  in case if you want to look into.

**Comment by dawidd6** [comment]
`certbot` is bottled now, so there should be no need for compilation on user machines.
Saying that, I think the issue is resolved.
