### ISSUE TITLE
nbdime (python package) failed to install

### ISSUE THREAD

**Issue by AlJohri** [Homebrew/linuxbrew-core#18623]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```
$ brew gist-logs nbdime
Error: undefined method `length' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/gist-logs.rb:145:in `gist_logs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 2.2.2-52-g40765b4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 40765b4a723afe38ac5aae23bad6973ae89ceb6b
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: e580217d76207456fd789808de0bcccd4ba3e92e
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /root/.cache/Homebrew
HOMEBREW_LOGS: /root/.cache/Homebrew/Logs
HOMEBREW_BREW_GIT_REMOTE: https://github.com/Homebrew/brew
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/linuxbrew-core
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: 16-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.24.1 => /usr/bin/git
Curl: 7.47.0 => /usr/bin/curl
Kernel: Linux 4.9.184-linuxkit x86_64 GNU/Linux
OS: Ubuntu 16.04.6 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: N/A
xorg: N/A
```

```
$ brew doctor
Your system is ready to brew.
```

## What you were trying to do (and why)

Trying to install `nbdime` on via docker.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

```
==> Installing dependencies for nbdime: python@3.8
==> Installing nbdime dependency: python@3.8
==> Downloading https://linuxbrew.bintray.com/bottles/python@3.8-3.8.1.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/80/806329adde447a54700fa7fb496632acc5f3f67e5209b6f1e1a326e6340b9f30?__gda__=exp=1578281672~hmac=5cfe7354eb2b60b9cff84d8b58105bf17c1f425d8612534a85776227dd9f8eea&response-content-disposition=attachment%3Bfilename%3D%22python%403.8-3.8.1.x86_64_linux.bottle.tar.gz%22&response-content-type=application%2Fgzip&requestInfo=U2FsdGVkX18BY6ONuv2l4DZOBZG85V7Pt_F4RPwDWwMtHo5-YRS6sdC0oYJz6wC61wBOt9vTGIrWejNtpQEM65CoFZvL2UGDsUwFjuWxm6JQCRhGCgJn62u9nqH0PPnH2M_56VSS1CdblZxfwaNzcQ&response-X-Checksum-Sha1=37747d7eb32cdfdcf5a44ae8dc971d2c0de9acbb&response-X-Checksum-Sha2=806329adde447a54700fa7fb496632acc5f3f67e5209b6f1e1a326e6340b9f30
==> Pouring python@3.8-3.8.1.x86_64_linux.bottle.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.1/bin --install-lib=/home/linuxbrew/.linuxbrew/lib/python3.8/site-packages --single-version-externally-managed --record=installed.txt
==> /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.1/bin --install-lib=/home/linuxbrew/.linuxbrew/lib/python3.8/site-packages --single-version-externally-managed --record=installed.txt
==> /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.1/bin --install-lib=/home/linuxbrew/.linuxbrew/lib/python3.8/site-packages --single-version-externally-managed --record=installed.txt
==> Caveats
Python has been installed as
  /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/python3

You can install Python packages with
  /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/pip3 install <package>
They will install into the site-package directory
  /home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages

See: https://docs.brew.sh/Homebrew-and-Python

python@3.8 is keg-only, which means it was not symlinked into /home/linuxbrew/.linuxbrew,
because this is an alternate version of another formula.

If you need to have python@3.8 first in your PATH run:
  echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/python@3.8/bin:$PATH"' >> ~/.bash_profile

For compilers to find python@3.8 you may need to set:
  export LDFLAGS="-L/home/linuxbrew/.linuxbrew/opt/python@3.8/lib"
  export CPPFLAGS="-I/home/linuxbrew/.linuxbrew/opt/python@3.8/include"

==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.1: 3,747 files, 69.1MB
==> Installing nbdime
==> Downloading https://files.pythonhosted.org/packages/1d/49/f173b8697f9868059739055c27f4263dcbcc2060669249b5e4d62765b3e5/nbdime-1.1.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b1/72/2d70c5a1de409ceb3a27ff2ec007ecdd5cc52239e7c74990e32af57affe9/virtualenv-15.2.0.tar.gz
==> python3.8 -c import setuptools... --no-user-cfg install --prefix=/tmp/nbdime--homebrew-virtualenv-20200106-20109-do3vi8/target --install-scripts=/tmp/nbdime--homebrew-virtualenv-20200106-20109-do3vi8/target/bin --single-version-externally-managed --record=installed.txt
==> python3.8 -s /tmp/nbdime--homebrew-virtualenv-20200106-20109-do3vi8/target/bin/virtualenv -p python3.8 /home/linuxbrew/.linuxbrew/Cellar/nbdime/1.1.0_1/libexec
==> Downloading https://files.pythonhosted.org/packages/26/34/0f3a5efac31f27fabce64645f8c609de9d925fe2915304d1a40f544cff0e/appnope-0.1.0.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/nbdime/1.1.0_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/nbdime--appnope-20200106-20109-1jk5c7z/appnope-0.1.0
Last 15 lines from /root/.cache/Homebrew/Logs/nbdime/03.pip:
  Found link https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl#sha256=993134f0475471b91452ca029d4390dc8f298ac63a712814f101cd1b6db46676 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*), version: 19.1.1
  Found link https://files.pythonhosted.org/packages/93/ab/f86b61bef7ab14909bd7ec3cd2178feb0a1c86d451bc9bccd5a1aedcde5f/pip-19.1.1.tar.gz#sha256=44d3d7d3d30a1eb65c7e5ff1173cdf8f7467850605ac7cc3707b6064bddd0958 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*), version: 19.1.1
  Found link https://files.pythonhosted.org/packages/3a/6f/35de4f49ae5c7fdb2b64097ab195020fb48faa8ad3a85386ece6953c11b1/pip-19.2-py2.py3-none-any.whl#sha256=468c67b0b1120cd0329dc72972cf0651310783a922e7609f3102bd5fb4acbf17 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.2
  Found link https://files.pythonhosted.org/packages/41/13/b6e68eae78405af6e4e9a93319ae5bb371057786f1590b157341f7542d7d/pip-19.2.tar.gz#sha256=aa6fdd80d13caac75d92b5eced06778712859b1606ba92d62389c11be12b2dad (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.2
  Found link https://files.pythonhosted.org/packages/62/ca/94d32a6516ed197a491d17d46595ce58a83cbb2fca280414e57cd86b84dc/pip-19.2.1-py2.py3-none-any.whl#sha256=80d7452630a67c1e7763b5f0a515690f2c1e9ad06dda48e0ae85b7fdf2f59d97 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.2.1
  Found link https://files.pythonhosted.org/packages/8b/8a/1b2aadd922db1afe6bc107b03de41d6d37a28a5923383e60695fba24ae81/pip-19.2.1.tar.gz#sha256=258d702483dd749400aec59c23d638a5b2249ae28a0f478b6cab12ad45681a80 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.2.1
  Found link https://files.pythonhosted.org/packages/8d/07/f7d7ced2f97ca3098c16565efbe6b15fafcba53e8d9bdb431e09140514b0/pip-19.2.2-py2.py3-none-any.whl#sha256=4b956bd8b7b481fc5fa222637ff6d0823a327e5118178f1ec47618a480e61997 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.2.2
  Found link https://files.pythonhosted.org/packages/aa/1a/62fb0b95b1572c76dbc3cc31124a8b6866cbe9139eb7659ac7349457cf7c/pip-19.2.2.tar.gz#sha256=e05103825871e210d50a44c7e448587b0ed99dd775d3ef586304c58f40224a53 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.2.2
  Found link https://files.pythonhosted.org/packages/30/db/9e38760b32e3e7f40cce46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl#sha256=340a0ba40fdeb16413914c0fcd8e0b4ebb0bf39a900ec80e11c05d836c05103f (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.2.3
  Found link https://files.pythonhosted.org/packages/00/9e/4c83a0950d8bdec0b4ca72afd2f9cea92d08eb7c1a768363f2ea458d08b4/pip-19.2.3.tar.gz#sha256=e7a31f147974362e6c82d84b91c7f2bdf57e4d3163d3d454e6c3e71944d67135 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.2.3
  Found link https://files.pythonhosted.org/packages/4a/08/6ca123073af4ebc4c5488a5bc8a010ac57aa39ce4d3c8a931ad504de4185/pip-19.3-py2.py3-none-any.whl#sha256=e100a7eccf085f0720b4478d3bb838e1c179b1e128ec01c0403f84e86e0e2dfb (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.3
  Found link https://files.pythonhosted.org/packages/af/7a/5dd1e6efc894613c432ce86f1011fcc3bbd8ac07dfeae6393b7b97f1de8b/pip-19.3.tar.gz#sha256=324d234b8f6124846b4e390df255cacbe09ce22791c3b714aa1ea6e44a4f2861 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.3
  Found link https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl#sha256=6917c65fc3769ecdc61405d3dfd97afdedd75808d200b2838d7d961cebc0c2c7 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.3.1
  Found link https://files.pythonhosted.org/packages/ce/ea/9b445176a65ae4ba22dce1d93e4b5fe182f953df71a145f557cffaffc1bf/pip-19.3.1.tar.gz#sha256=21207d76c1031e517668898a6b46a9fb1501c7a4710ef5dfd6a40ad9e6757ea7 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.3.1
Given no hashes to check 131 links for project 'pip': discarding no candidates

READ THIS: https://docs.brew.sh/Troubleshooting

Installing nbdime has failed!
```

  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew install` commands)

```
docker run -it linuxbrew/brew brew install nbdime
```

**Comment by issyl0** [comment]
Thanks for raising this. I've pushed a potential fix in #18657, let's see what CI thinks.
