### ISSUE TITLE
Is there a way to get python with tk?

### ISSUE THREAD

**Issue by pgcudahy** [Homebrew/linuxbrew-core#20181]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ X] ran `brew update` and can still reproduce the problem?
- [ X] ran `brew doctor`, fixed all issues and can still reproduce the problem?

## What you were trying to do (and why)
Use matplotlib.pyplot within python 

## What happened (include command output)
```
$python
Python 3.7.7 (default, Apr 20 2020, 05:55:00) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/linuxbrew/.linuxbrew/lib/python3.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/linuxbrew/.linuxbrew/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/home/linuxbrew/.linuxbrew/lib/python3.7/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/home/linuxbrew/.linuxbrew/lib/python3.7/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/home/linuxbrew/.linuxbrew/lib/python3.7/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/home/linuxbrew/.linuxbrew/lib/python3.7/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/linuxbrew/.linuxbrew/lib/python3.7/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```
The same issue was at https://github.com/Homebrew/linuxbrew-core/issues/11256, but seems to have fizzled out. Is there any way forward on this?

**Comment by iMichka** [comment]
Hi. Yes, we gave up on the previous approach because it was too complex.

I discussed this with some maintainers lately. The strategy would be to have something similar to what we did with `git-gui`: we have the lightweight `git` formula, and then the heavy `git-gui` one.

I would like to have the standard `python` formula, and then a more heavy `python-tcl-tk` formula.

Would you like to try to create a pull request for that?

**Comment by iMichka** [comment]
Looks like we made no progress on this and it is on our really low priority list. Sorry we could not help you further. I'll close this issues as nobody is currently working on this.
