### ISSUE TITLE
osmfilter bottle seems to be built without zlib, thus missing osmconvert

### ISSUE THREAD

**Issue by kkdd** [Homebrew/linuxbrew-core#20353]
Hello
osmfilter-0.9.x86_64_linux.bottle.tar.gz should be built for osmfilter, osmupdate and osmconvert commands.

But it seems to be built only for osmfilter and osmupdate but osmconvert presumably by not finding zlib, originating from ```AC_CHECK_LIB(z, gzopen, [enable_osmconvert=yes], [enable_osmconvert=no])``` in [configure.ac](https://gitlab.com/osm-c-tools/osmctools/-/blob/master/configure.ac).

```
$ brew install osmfilter
==> Downloading https://linuxbrew.bintray.com/bottles/osmfilter-0.9.x86_64_linux
Already downloaded: /home/kkdd/.cache/Homebrew/downloads/84b6dc7048f4cede712a95d25867f6d64c7e3adcac6886254095f7f7b1b4bcd5--osmfilter-0.9.x86_64_linux.bottle.tar.gz
==> Pouring osmfilter-0.9.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/osmfilter/0.9: 7 files, 447.4KB
$
$ osmconvert -h
Command 'osmconvert' not found, but can be installed with:
sudo apt install osmctools
$
$ brew info osmfilter
osmfilter: stable 0.9 (bottled), HEAD
Command-line tool to filter OpenStreetMap files for specific tags
https://wiki.openstreetmap.org/wiki/Osmfilter
Not installed
From: https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/osmfilter.rb
==> Dependencies
Build: autoconf ✘, automake ✘
Required: zlib ✔
==> Options
--HEAD
        Install HEAD version
==> Analytics
install: 0 (30 days), 2 (90 days), 5 (365 days)
install-on-request: 0 (30 days), 2 (90 days), 5 (365 days)
build-error: 0 (30 days)
$
$ brew test osmfilter
Testing osmfilter
==> Downloading https://download.gisgraphy.com/openstreetmap/pbf/AD.tar.bz2
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/osmfilter/0.9/bin/osmconvert AD -o=test.o5
Last 15 lines from /home/kkdd/.cache/Homebrew/Logs/osmfilter/test.01.osmconvert:
2020-05-13 21:22:42 +0900

/home/linuxbrew/.linuxbrew/Cellar/osmfilter/0.9/bin/osmconvert
AD
-o=test.o5m

Error: osmfilter: failed
An exception occurred within a child process:
  BuildError: Failed executing: /home/linuxbrew/.linuxbrew/Cellar/osmfilter/0.9/bin/osmconvert AD -o=test.o5m
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2013:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1951:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1951:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/osmfilter.rb:37:in `block (2 levels) in <class:Osmfilter>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:111:in `block in unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:185:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:184:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:106:in `unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:81:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/osmfilter.rb:36:in `block in <class:Osmfilter>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1821:in `block (3 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1820:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:888:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1819:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2063:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2062:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1813:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:35:in `block in <main>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:34:in `<main>'
$
```

# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

**Comment by kkdd** [comment]
PS. In the case of building from the source (i.e., ```brew install osmfilter --build-from-source```), osmconvert is built successfully:

```
$ osmconvert -h

osmconvert 0.8.10  Parameter Overview
(Please use  --help  to get more information.)
 :
 :
```

**Comment by sjackman** [comment]
Feel free to open an a PR that adds `uses_from_macos "zlib"` to the formula for `osmfilter`. Try `brew edit osmfilter` and see https://docs.brew.sh/#contributors

**Comment by kkdd** [comment]
Thank for your suggestion.
It already has ``uses_from_macos "zlib"```, however.

```
$ brew cat osmfilter | grep zlib
  uses_from_macos "zlib"
```

**Comment by sjackman** [comment]
Try troubleshooting the issue using `brew install -dv osmfilter`. If you can reproduce the issue outside of Homebrew, please open an issue with the upstream developers of `osmfilter`. If you're able to find a solution to this issue, please open a PR to Linuxbrew-core. Best of luck!

**Comment by kkdd** [comment]
Thank you for suggestion.
It is reproduced:

```
$ brew uninstall osmfilter
$ brew install -dv osmfilter
$ osmconvert -h
Command 'osmconvert' not found, but can be installed with:
sudo apt install osmctools
$
```

I am afraid that this would be a linuxbrew issue.
The formula seems to fail to find zlib when building for Linux.

**Comment by kkdd** [comment]
open PR: https://github.com/Homebrew/linuxbrew-core/pull/20402
