### ISSUE TITLE
ocrmypdf build fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by clpo13** [Homebrew/linuxbrew-core#20908]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrade `ocrmypdf` from 10.1.0 to the latest version (10.3.1 at the time of writing).

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
$ brew upgrade ocrmypdf
Updating Homebrew...
==> Upgrading 1 outdated package:
ocrmypdf 10.1.0 -> 10.3.1
==> Upgrading ocrmypdf 10.1.0 -> 10.3.1 
==> Downloading https://files.pythonhosted.org/packages/b1/72/2d70c5a1de409ceb3a27ff2ec007ecdd5cc52239e7c74990e32af57affe9/virtualenv-15.2.0.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/e390edd594d1668ad899868951573cc02842e8f82003ec75bd388377d3a3f373--virtualenv-15.2.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/54/1d/15eae71ab444bd88a1d69f19592dcf32b9e3166ecf427dd9243ef0d3b7bc/cffi-1.14.1.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/099d0510b0539907c313f58ed8e787a4c0df50007bc623d6aaa6b23be9df0afa--cffi-1.14.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/de28644dd0ba2aaf30228e9b28ba90366e333e7a34e1b1f97cf85d0edd0cb278--chardet-3.0.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/84/1b/1ecdd371fa68839cfbda15cc671d0f6c92d2c42688df995a9bf6e36f3511/coloredlogs-14.0.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/b5a76a3adab09521c3b99134fbf12e9f01f461ad20e6122814f8173b46caae52--coloredlogs-14.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/bf/ac/552fc8729d90393845cc3a2062facf4a89dcbe206fa78771d60ddaae7554/cryptography-3.0.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/8a401ef077d532395ec8d7a36406e81486cc5af52567801486a940f4449d39a1--cryptography-3.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/6c/19/8e3b4c6fa7cca4788817db398c05274d98ecc6a35e0eaad2846fde90c863/humanfriendly-8.2.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/15a17e6166983958d243d9792572e85a204e50a04c08755d66f350b59828c904--humanfriendly-8.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/65/12/6ee1a77614df6decefd88f781cf95b73acf93f0cc9eb03bd5042d116b85d/img2pdf-0.3.6.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/d5c80473d8708aaa9963e773d94d75749f810762ae473f31659a5258e1c2a981--img2pdf-0.3.6.tar.gz
==> Downloading https://files.pythonhosted.org/packages/2c/4d/3ec1ea8512a7fbf57f02dee3035e2cce2d63d0e9c0ab8e4e376e01452597/lxml-4.5.2.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/9546456c821c2995c4a6e2b083cd90b55b05f8708f67751722ae1f7d671b709a--lxml-4.5.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/34/4a/bc38040c4a970870ccbef975bae2b6b1bccaa2d308e61111203cccc58e89/pdfminer.six-20200726.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/cafdc9f5a78956b1e6028768df5348a2c231ce69eb5170fcb6d47b2f70484b7e--pdfminer.six-20200726.tar.gz
==> Downloading https://files.pythonhosted.org/packages/23/a8/4df6b1dfaabd8cef718cd112cb8d81d9788ecfe838f911546a3ae0dd5529/pikepdf-1.17.3.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/a635878421d0ea2f0a26a1ecca047f7be61c1f431b7056d3323beb20b5dc217a--pikepdf-1.17.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/3e/02/b09732ca4b14405ff159c470a612979acfc6e8645dc32f83ea0129709f7a/Pillow-7.2.0.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/899e7f7e8e7a38057e7a83834d8fca72e3486ad859576c9cf08daccf45ec7979--Pillow-7.2.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/f8/04/7a8542bed4b16a65c2714bf76cf5a0b026157da7f75e87cc88774aa10b14/pluggy-0.13.1.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/d8bb8e5c00ea85bc0212cceeab3b2569a2e57713853bb37d907d65ae06376d32--pluggy-0.13.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/0f/86/e19659527668d70be91d0369aeaa055b4eb396b0f387a4f92293a20035bd/pycparser-2.20.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/79095b22470240738563ecd6e5991087cf18e4acb8af487f16677f8864198bce--pycparser-2.20.tar.gz
==> Downloading https://files.pythonhosted.org/packages/52/09/85beb77f215bf47de07d2041731bdba55d7290a9304daad2eda935d3337f/reportlab-3.5.46.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/d24aee767970c7c52033cf1a1a39cf11c0560e6b72a562dc69c5e23e47a22125--reportlab-3.5.46.tar.gz
==> Downloading https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/e99698a932bde9f5fb8ca552923ae339984f284e1c7764df95c12175f573c0d7--six-1.15.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/3b/fb/48f6fa11e4953c530b09fa0f2976df5234b0eaabcd158625c3e73535aeb8/sortedcontainers-2.2.2.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/68c1f0f43a84399ed345f4e63ced15be514d7a889d4b1e2a5842aadfd8f762fc--sortedcontainers-2.2.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/71/6c/6530032ec26dddd47bb9e052781bcbbcaa560f05d10cdaf365ecb990d220/tqdm-4.48.0.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/bf50c216cbeac5f41173b32444439e6587c26ad7e50ed384b6edaaaf41f75327--tqdm-4.48.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/8b/6a/079143b7677e5d356270e2fee0fe5b71e6d900a51c360d2b49d8356f134e/ocrmypdf-10.3.1.tar.gz
Already downloaded: /home/cody/.cache/Homebrew/downloads/86f64617143ea85cb6c038b0556aef13f96c4fcc18a140a60f9dd5af23dc5583--ocrmypdf-10.3.1.tar.gz
==> /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/ocrmypdf--homebrew-virtualenv-20200807-27113-xk8wge/target --install-scripts=/tmp/ocrmypdf--homebrew-virtualenv-20200807-27113-xk8wge/target/bin --single-version-externally-managed --record=installed.txt
==> /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/python3 -s /tmp/ocrmypdf--homebrew-virtualenv-20200807-27113-xk8wge/target/bin/virtualenv -p /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/python3 /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/10.3.1/libexec
==> /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/10.3.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/ocrmypdf--Pillow-20200807-27113-n93986/Pillow-7.2.0
==> /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/10.3.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/ocrmypdf--cffi-20200807-27113-46adf1/cffi-1.14.1
==> /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/10.3.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/ocrmypdf--chardet-20200807-27113-1cs442s/chardet-3.0.4
==> /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/10.3.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/ocrmypdf--coloredlogs-20200807-27113-nmvafb/coloredlogs-14.0
==> /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/10.3.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/ocrmypdf--cryptography-20200807-27113-1usb5ft/cryptography-3.0
==> /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/10.3.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/ocrmypdf--humanfriendly-20200807-27113-1vitsnd/humanfriendly-8.2
==> /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/10.3.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/ocrmypdf--img2pdf-20200807-27113-1qwix32/img2pdf-0.3.6
==> /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/10.3.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/ocrmypdf--lxml-20200807-27113-1lftnfr/lxml-4.5.2
==> /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/10.3.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/ocrmypdf--pdfminer.six-20200807-27113-1g9x310/pdfminer.six-20200726
==> /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/10.3.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/ocrmypdf--pikepdf-20200807-27113-9bvs62/pikepdf-1.17.3
Last 15 lines from /home/cody/.cache/Homebrew/Logs/ocrmypdf/12.pip:
  error: command 'gcc-5' failed with exit status 1
  Building wheel for pikepdf (PEP 517): finished with status 'error'
  ERROR: Failed building wheel for pikepdf
Failed to build pikepdf
ERROR: Could not build wheels for pikepdf which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/10.3.1/libexec/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/10.3.1/libexec/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/10.3.1/libexec/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 365, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for pikepdf which use PEP 517 and cannot be installed directly
Removed build tracker: '/tmp/pip-req-tracker-mska4uqx'

READ THIS: https://docs.brew.sh/Troubleshooting
  </pre>
</details>

Full logs at https://gist.github.com/clpo13/d9bd3eb667d6e839530417cba9585bc8. The relevant error is cut off above:

```
gcc-5 -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -DVERSION_INFO="1.17.3" -I/tmp/pip-build-env-q4evs58_/overlay/lib/python3.8/site-packages/pybind11/include -I/home/linuxbrew/.linuxbrew/opt/python@3.8/include/python3.8 -c src/qpdf/object_convert.cpp -o build/temp.linux-x86_64-3.8/src/qpdf/object_convert.o -std=c++14 -fvisibility=hidden
src/qpdf/object_convert.cpp: In function 'QPDFObjectHandle objecthandle_encode(pybind11::handle)':
src/qpdf/object_convert.cpp:119:33: error: 'isfinite' was not declared in this scope
         if (! isfinite(as_double))
                                 ^
src/qpdf/object_convert.cpp:119:33: note: suggested alternative:
In file included from src/qpdf/object_convert.cpp:15:0:
/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_7/include/c++/5.5.0/cmath:604:5: note:   'std::isfinite'
     isfinite(_Tp __x)
     ^
error: command 'gcc-5' failed with exit status 1
Building wheel for pikepdf (PEP 517): finished with status 'error'
ERROR: Failed building wheel for pikepdf
```

Troubleshooting the `pikepdf` dependency shows that this error occurs with GCC 5 but not GCC 6 or later. I tried selecting a different compiler with `fails_with :gcc => '5'` in the formula definition, which resulted in `pikepdf` building successfully, but then the `reportlab` dependency fails to build due to not being able to find `ft2build.h`. I haven't done any troubleshooting of that, though, but the logs are at https://gist.github.com/clpo13/4e7103b1af3d1182da87e82d227562ac.

## What you expected to happen

`ocrmypdf` to be upgraded to 10.3.1.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew upgrade ocrmypdf`

**Comment by clpo13** [comment]
The problem with pikepdf was fixed by pikepdf/pikepdf#119 and is no longer occurring as of ocrmypdf 11.0.1. However, the build still fails for me on the reportlab dependency:

```
    building 'reportlab.graphics._renderPM' extension
    creating build/temp.linux-x86_64-3.8/src/rl_addons/renderPM
    creating build/temp.linux-x86_64-3.8/src/rl_addons/renderPM/gt1
    creating build/temp.linux-x86_64-3.8/src/rl_addons/renderPM/libart_lgpl
    gcc-5 -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -DRENDERPM_FT -DLIBART_COMPILATION -DLIBART_VERSION="2.3.21" -Isrc/rl_addons/renderPM -Isrc/rl_addons/renderPM/libart_lgpl -Isrc/rl_addons/renderPM/gt1 -I/usr/include/freetype2 -I/home/linuxbrew/.linuxbrew/opt/python@3.8/include/python3.8 -c src/rl_addons/renderPM/_renderPM.c -o build/temp.linux-x86_64-3.8/src/rl_addons/renderPM/_renderPM.o
    src/rl_addons/renderPM/_renderPM.c:147:22: fatal error: ft2build.h: No such file or directory
    compilation terminated.
    error: command 'gcc-5' failed with exit status 1
    Running setup.py install for reportlab: finished with status 'error'
ERROR: Command errored out with exit status 1: /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/11.0.1/libexec/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-si9_27lm/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-si9_27lm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2b0qliur/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/11.0.1/libexec/include/site/python3.8/reportlab Check the logs for full command output.
```

**Comment by jonchang** [comment]
Bintray is having an outage. We'll try again later. https://status.bintray.com/incidents/svfxknx0pkc4
