### ISSUE TITLE
Error: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by dhaugli** [Homebrew/linuxbrew-core#22070]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [Yes ] ran `brew update` and can still reproduce the problem?
- [Yes ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ Didnt work] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ Included ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
I am trying to run brew update and brew upgrade to update my software installed through brew

## What happened (include command output)

 david@computer  ~  brew update && brew upgrade
Already up-to-date.
Error: invalid byte sequence in UTF-8
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `block (2 levels) in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `block in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:151:in `cask_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:99:in `commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:198:in `rebuild_commands_completion_list'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/update-report.rb:153:in `update_report'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'

<details>
  <summary>Command output</summary>
  <pre>

I tried running brew config and brew doctor this is the following output.
Brew config: 
brew config
HOMEBREW_VERSION: 2.7.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: dad7dc6a1498b80770d98f2d7cd6fb927c300bbb
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: afb28c21883bd1dad0c72bfc7032029485fd695f
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit skylake
Clang: N/A
Git: 2.27.0 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.8.0-33-generic x86_64 GNU/Linux
OS: Ubuntu 20.10 (groovy)
Host glibc: 2.32
/usr/bin/gcc: 10.2.0
/usr/bin/ruby: 2.7.1
glibc: N/A
gcc: N/A
xorg: N/A

Brew Doctor: 
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libice instead of deprecated linuxbrew/xorg/libice
Warning: Use libsm instead of deprecated linuxbrew/xorg/libsm
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libice instead of deprecated linuxbrew/xorg/libice
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use libxfixes instead of deprecated linuxbrew/xorg/libxfixes
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto

I also tried through google search to update those deprecated modules.

rew update && brew cleanup && brew untap linuxbrew/xorg/libpthread-stubs
brew update && brew cleanup && brew untap linuxbrew/xorg/xorgproto
brew update && brew cleanup && brew untap linuxbrew/xorg/libxau
brew update && brew cleanup && brew untap linuxbrew/xorg/libx11
brew update && brew cleanup && brew untap linuxbrew/xorg/libxext
brew update && brew cleanup && brew untap linuxbrew/xorg/libice
brew update && brew cleanup && brew untap linuxbrew/xorg/libsm4
brew update && brew cleanup && brew untap linuxbrew/xorg/libxfixes
Already up-to-date.
Error: invalid byte sequence in UTF-8
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `block (2 levels) in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `block in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:151:in `cask_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:99:in `commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:198:in `rebuild_commands_completion_list'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/update-report.rb:153:in `update_report'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
Already up-to-date.
Error: invalid byte sequence in UTF-8
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `block (2 levels) in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `block in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:151:in `cask_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:99:in `commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:198:in `rebuild_commands_completion_list'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/update-report.rb:153:in `update_report'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
Already up-to-date.
Error: invalid byte sequence in UTF-8
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `block (2 levels) in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `block in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:151:in `cask_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:99:in `commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:198:in `rebuild_commands_completion_list'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/update-report.rb:153:in `update_report'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
Already up-to-date.
Error: invalid byte sequence in UTF-8
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `block (2 levels) in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `block in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:151:in `cask_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:99:in `commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:198:in `rebuild_commands_completion_list'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/update-report.rb:153:in `update_report'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
Already up-to-date.
Error: invalid byte sequence in UTF-8
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `block (2 levels) in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `block in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:151:in `cask_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:99:in `commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:198:in `rebuild_commands_completion_list'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/update-report.rb:153:in `update_report'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
Already up-to-date.
Error: invalid byte sequence in UTF-8
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `block (2 levels) in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `block in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:151:in `cask_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:99:in `commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:198:in `rebuild_commands_completion_list'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/update-report.rb:153:in `update_report'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
Already up-to-date.
Error: invalid byte sequence in UTF-8
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `block (2 levels) in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `block in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:151:in `cask_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:99:in `commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:198:in `rebuild_commands_completion_list'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/update-report.rb:153:in `update_report'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
Already up-to-date.
Error: invalid byte sequence in UTF-8
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `block (2 levels) in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `block in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:151:in `cask_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:99:in `commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:198:in `rebuild_commands_completion_list'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/update-report.rb:153:in `update_report'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'

Because this is disturbing my other applications like Azure CLI, that is obviously written in Python so trying to run some commands there results in python issues. 

  </pre>
</details>

## What you expected to happen

My installed software should have been updated

## Step-by-step reproduction instructions (by running `brew install` commands)

brew update && brew upgrade

**Comment by dhaugli** [comment]
Ok, I have reinstalled brew. so now brew doctor reports "Your system is ready to brew". 
But when I run brew update or brew upgrade I still get:

✘ david@computer  ~  brew upgrade
Error: invalid byte sequence in UTF-8
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:167:in `block (2 levels) in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:165:in `block in cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:164:in `cask_external_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:151:in `cask_commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:99:in `commands'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:198:in `rebuild_commands_completion_list'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/update-report.rb:153:in `update_report'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
