### ISSUE TITLE
magic-wormhole cannot be installed on Linux

### ISSUE THREAD

**Issue by robolange** [Homebrew/linuxbrew-core#22654]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.0.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 59ada80ca740e72d29e625079395ee91cae4b3cf
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: fd802f2485ed78c5c1f70ae8e541a08bcc73f124
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit haswell
Clang: N/A
Git: 2.20.1 => /usr/bin/git
Curl: 7.64.0 => /usr/bin/curl
Kernel: Linux 4.19.0-14-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 10 (buster) (buster)
Host glibc: 2.28
/usr/bin/gcc: 8.3.0
/usr/bin/ruby: 2.5.5
glibc: N/A
gcc@5: N/A
xorg: N/A
---
Your system is ready to brew.
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I had magic-wormhole (prior to 0.12.0_4) installed on my system and I tried to upgrade it. The upgrade failed repeatably. I uninstalled and cleared all homebrew, installed homebrew clean, and tried again. The install fails repeatably with the same error. I also have a Mac, and I was able to successfully install magic-wormhole on it.

### What happened (include all command output)?

```
$ brew install magic-wormhole
==> Downloading https://files.pythonhosted.org/packages/f0/cb/80a4a274df7da7b8baf083249b0890a0579374c3d74b5ac0ee9291f912dc/attrs-20.3.0.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/e710e67164f7f9e6dac8fa881e0f83e0819293882d51baf1b442099b6c4954a7--attrs-20.3.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/4c/9e/f5bdfb55d1eab67c4b6d24d1397f95feec792071ff1b2f5a893d6d5247f3/autobahn-21.3.1.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/83f01594547ba12de9644771e53c69617d45b29367b6f1e0d028baca9ee0b363--autobahn-21.3.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/80/c5/82c63bad570f4ef745cc5c2f0713c8eddcd07153b4bee7f72a8dc9f9384b/Automat-20.2.0.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/0ebc7eef885f978672585211ab613c76db1dfb1ca59ae3671de7c1fac992020a--Automat-20.2.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/a8/20/025f59f929bbcaa579704f443a438135918484fffaacfaddba776b374563/cffi-1.14.5.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/720a5f286c07cd84c16b610605e24a8746156376520b56b1389c94786447843e--cffi-1.14.5.tar.gz
==> Downloading https://files.pythonhosted.org/packages/27/6f/be940c8b1f1d69daceeb0032fee6c34d7bd70e3e649ccac0951500b4720e/click-7.1.2.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/729f15182b3d73a61df6c5b70fb07736c3a57abd09b7fde46af074f5787e42dd--click-7.1.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/95/f1/207a0a478c4bb34b1b49d5915e2db574cadc415c9ac3a7ef17e29b2e8951/constantly-15.1.0.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/4f83088b9b300bfd7783ef1094186caf0d57ff4bb134ee8fe643ee6cae7ff604--constantly-15.1.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/fa/2d/2154d8cb773064570f48ec0b60258a4522490fcb115a6c7c9423482ca993/cryptography-3.4.6.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/3d664bb41598e5779469edeea1b41fe683f5ca145c2fa6841b6a98be8f0afe48--cryptography-3.4.6.tar.gz
==> Downloading https://files.pythonhosted.org/packages/c3/be/327e072850db181ce56afd51e26ec7aa5659b18466c709fa5ea2548c935f/hkdf-0.0.3.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/b570093781329d748f40c1e177b36972b105e6cbda53bf448faa1c245d84bf41--hkdf-0.0.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/64/f1/2fb00b5db6ece093d47fa8d0afc0634683c06bc8f0d0dd2a2457905d8456/humanize-3.2.0.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/6785a87a2f806092fc865626f1a73c0b60e284221f09962fee52e16929ab57b8--humanize-3.2.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/3a/51/1947bd81d75af87e3bb9e34593a4cf118115a8feb451ce7a69044ef1412e/hyperlink-21.0.0.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/713ad07c0fae0b13c0b38f717e713af7381c4e6dc59f78fb39bdaac96cc402ba--hyperlink-21.0.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/9f/24/1444ee2c9aee531783c031072a273182109c6800320868ab87675d147a05/idna-3.1.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/3f8a5174b6fedc6e035085b7e49bea4c6b804640b3346cb1172f3c6947bfabda--idna-3.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/4f/c5/430765c697afc217c8491785de321a21fa4d983dda14bcd82feb965b0593/incremental-21.3.0.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/c88dc621c55bd5e87c9730afce9f3dd75be9003c9d4eb05e3b92c6e58bd44bb8--incremental-21.3.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/a4/db/fffec68299e6d7bad3d504147f9094830b704527a7fc098b721d38cc7fa7/pyasn1-0.4.8.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/7e556aaeae52fad43aebfee1b7bb3bf7b9c68223c18734536277589c7e7f7b49--pyasn1-0.4.8.tar.gz
==> Downloading https://files.pythonhosted.org/packages/88/87/72eb9ccf8a58021c542de2588a867dbefc7556e14b2866d1e40e9e2b587e/pyasn1-modules-0.2.8.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/17b24583ffb54a51ff754b5dd0e70b5c3ee77c0cd45830081bf91509d1990ff4--pyasn1-modules-0.2.8.tar.gz
==> Downloading https://files.pythonhosted.org/packages/0f/86/e19659527668d70be91d0369aeaa055b4eb396b0f387a4f92293a20035bd/pycparser-2.20.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/79095b22470240738563ecd6e5991087cf18e4acb8af487f16677f8864198bce--pycparser-2.20.tar.gz
==> Downloading https://files.pythonhosted.org/packages/cf/5a/25aeb636baeceab15c8e57e66b8aa930c011ec1c035f284170cacb05025e/PyNaCl-1.4.0.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/92f8bf9befcfdc97591cfe26b7a99d677375c1eeede137cd904f770f16c420bb--PyNaCl-1.4.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/98/cd/cbc9c152daba9b5de6094a185c66f1c6eb91c507f378bb7cad83d623ea88/pyOpenSSL-20.0.1.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/6e55c2d0aa5cf6931e107032cdf632e90d3cbc49718dd663374118bc8826b12f--pyOpenSSL-20.0.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/9a/3d/9eb0563e066ea0540cf580695593ab079376e920016d4d1b3ff2fd8abf4b/service_identity-18.1.0.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/12d89b1da68b105e08628626560eeeafd6fd717c1f02a3f6af732baa31f58d60--service_identity-18.1.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/e99698a932bde9f5fb8ca552923ae339984f284e1c7764df95c12175f573c0d7--six-1.15.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/60/0b/bb5eca8e18c38a10b1c207bbe6103df091e5cf7b3e5fdc0efbcad7b85b60/spake2-0.8.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/8994861c6751f28e55ac01dd1c3519aad7086f74ea29acb19e54bda01019e7e1--spake2-0.8.tar.gz
==> Downloading https://files.pythonhosted.org/packages/ef/58/60cc1e9af5714d1b86062f6dc00c5dd6973c902da6259f930b9c6e7a3430/tqdm-4.59.0.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/33c913bc0cdf16dec655fbef23faf13143e1c52e260e9d2c8890f60ee0a74818--tqdm-4.59.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/c2/41/3f30da0f7025480eff8feb9ef0927c6db6bbbf6e64985cac77ee0210a903/Twisted-21.2.0.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/562c16d4ea536d7d85459b2cc93801517e516bd920867f0e3f4535bc73750124--Twisted-21.2.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/c5/39/2e715062283f8443d8ceeea32276db71741664d78d43c3edd3675498e926/txaio-21.2.1.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/08425aadd59e0a1f22f14bba1a6f0fe10d203adb398835ebc140f815e3680aa9--txaio-21.2.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/a5/12/4d39a81dd2f60d7c54d2be5484054d668fed27741bee02ebebe55123838a/txtorcon-20.0.0.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/89a3b69709f733093a513001a2d81ff02680bc94eebae52192ed4dc080850cf9--txtorcon-20.0.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/ed/46/e298a50dde405e1c202e316fa6a3015ff9288423661d7ea5e8f22f589071/wheel-0.36.2.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/2628149c388cda23d833947d9d838f27eba9442101b2958948fbe661e96b689b--wheel-0.36.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/84/21/80cdc749908ebf2719a9063eddcc02b668fbc62d200c1f1a4d92aaaba76b/zope.interface-5.2.0.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/ff9d57f3bef0aa49bce05e7c1565826be68c318f502a1e256de83d25e4b139cd--zope.interface-5.2.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/d4/62/5e4a86f7c4b111e016577f1b304063ebe604f430db15465ac58b13993608/magic-wormhole-0.12.0.tar.gz
Already downloaded: /home/local/.cache/Homebrew/downloads/286b8ddb3e8fd01bec4a6bbe3024754f81424a8edd6dc0f9c916207c185a7264--magic-wormhole-0.12.0.tar.gz
==> python3 -m venv /home/linuxbrew/.linuxbrew/Cellar/magic-wormhole/0.12.0_4/libexec
==> /home/linuxbrew/.linuxbrew/Cellar/magic-wormhole/0.12.0_4/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/magic-wormhole--wheel-20210321-30024-w
==> /home/linuxbrew/.linuxbrew/Cellar/magic-wormhole/0.12.0_4/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/magic-wormhole--cffi-20210321-30024-10
Error: An exception occurred within a child process:
  RuntimeError: Will not overwrite /home/linuxbrew/.linuxbrew/Cellar/magic-wormhole/0.12.0_4/libexec/lib/python3.9/site-packages/homebrew_deps.pth
```

### What did you expect to happen?

I expected magic-wormhole to install.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew install magic-wormhole
```

**Comment by danielnachun** [comment]
Does anyone in @Homebrew/maintainers who knows about our Python `virtualenv` system understand the error seen here?  I can reproduce this in our Docker CI but I don't really understand why it's happening and it looks to be some sort of issue with HomeBrew because it refers to `homebrew_deps.pth`.

**Comment by mistydemeo** [comment]
Do you mind rerunning it as `brew install magic-wormhole --debug`? The backtrace would be helpful to identify what exactly is happening.

**Comment by danielnachun** [comment]
This is what I see when I run in the CI Docker environment: 

```
tar xof /root/.cache/Homebrew/downloads/286b8ddb3e8fd01bec4a6bbe3024754f81424a8edd6dc0f9c916207c185a7264--magic-wormhole-0.12.0.tar.gz -C /tmp/d20210330-9169-mlsq24
cp -pR /tmp/d20210330-9169-mlsq24/magic-wormhole-0.12.0/. /tmp/magic-wormhole-20210330-9169-1nz211z/magic-wormhole-0.12.0
==> python3 -m venv /home/linuxbrew/.linuxbrew/Cellar/magic-wormhole/0.12.0_4/libexec
tar xof /root/.cache/Homebrew/downloads/2628149c388cda23d833947d9d838f27eba9442101b2958948fbe661e96b689b--wheel-0.36.2.tar.gz -C /tmp/d20210330-9169-6b065b
cp -pR /tmp/d20210330-9169-6b065b/wheel-0.36.2/. /tmp/magic-wormhole--wheel-20210330-9169-13u7ys5/wheel-0.36.2
==> /home/linuxbrew/.linuxbrew/Cellar/magic-wormhole/0.12.0_4/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/magic-wormhole--wheel-20210330-9169-13
tar xof /root/.cache/Homebrew/downloads/720a5f286c07cd84c16b610605e24a8746156376520b56b1389c94786447843e--cffi-1.14.5.tar.gz -C /tmp/d20210330-9169-167t7dt
cp -pR /tmp/d20210330-9169-167t7dt/cffi-1.14.5/. /tmp/magic-wormhole--cffi-20210330-9169-15j1j08/cffi-1.14.5
==> /home/linuxbrew/.linuxbrew/Cellar/magic-wormhole/0.12.0_4/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/magic-wormhole--cffi-20210330-9169-15j
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:18:in `raise'
RuntimeError: Will not overwrite /home/linuxbrew/.linuxbrew/Cellar/magic-wormhole/0.12.0_4/libexec/lib/python3.9/site-packages/homebrew_deps.pth
```

The corresponding lines the formula which generate this should be:
```
    venv = virtualenv_create(libexec, "python3")
    venv.pip_install resource("wheel")
    venv.pip_install resource("cffi")
    virtualenv_install_with_resources
```
although it never makes to `virtualenv_install_with_resources` I think.

It seem like maybe the issue is that it doesn't like us trying to install two difference resources with `venv.pip_install`, because something gets overwritten for the second resource install?

**Comment by mistydemeo** [comment]
Hm, it's still missing a backtrace from that line - it'd help to know what methods it's stepping through when that happens.

In context, it's probably the call to writing `homebrew.pth here: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula.rb#L1980 But that *should* be safe to call repeatedly in this context, or so it seems to be when I was testing locally.

**Comment by danielnachun** [comment]
Whoops, dropped the ball on that. I think this is the backtrace you wanted:

```
RuntimeError: Will not overwrite /home/linuxbrew/.linuxbrew/Cellar/magic-wormhole/0.12.0_4/libexec/lib/python3.9/site-packages/homebrew_deps.pth
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 3
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:18:in `raise'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:176:in `write'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/language/python.rb:148:in `virtualenv_create'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/language/python.rb:185:in `virtualenv_install_with_resources'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/magic-wormhole.rb:164:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:30:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:104:in `debrew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:30:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:175:in `block (2 levels) in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1241:in `block in brew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2287:in `block (2 levels) in stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2286:in `block in stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:121:in `block (2 levels) in unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/download_strategy.rb:100:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/download_strategy.rb:100:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/download_strategy.rb:87:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:117:in `block in unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:198:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2266:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1234:in `brew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:139:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:134:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:227:in `<main>'
```

**Comment by iMichka** [comment]
Someone mentionned on Slack that this was sometimes happening on mac too for this formula, but the failure has been more flacky there.

**Comment by danielnachun** [comment]
I don't know if this is relevant it seems in https://github.com/Homebrew/brew/blob/e5bda4e781bdd74240b2f01df0f01ab5477e3300/Library/Homebrew/formula.rb#L1978 there are multiple references to python 2.7.  That could be a problem for us given that we don't support Python 2 at all on Linux.

**Comment by Rylan12** [comment]
Ah, interesting. @carlocab and I were looking into whether `virtualenv_install_with_resources` can be called after `virtualenv_create`. I think the problem is that `virtualenv_install_with_resources` re-creates the Virtualenv that was created in the `venv = virtualenv_create(libexec, "python3")` command.

[`virtualenv_install_with_resources`](https://github.com/Homebrew/brew/blob/e5bda4e781bdd74240b2f01df0f01ab5477e3300/Library/Homebrew/language/python.rb#L175-L189) calls [`virtualenv_create`](https://github.com/Homebrew/brew/blob/e5bda4e781bdd74240b2f01df0f01ab5477e3300/Library/Homebrew/language/python.rb#L129-L152) to create the venv. This, in turn, runs [`Virtualenv#create`](https://github.com/Homebrew/brew/blob/e5bda4e781bdd74240b2f01df0f01ab5477e3300/Library/Homebrew/language/python.rb#L216-L243). `Virtualenv#create` exits early because the virtualenv exists but `virtualenv_create` will continue to execute, re-writing the `homebrew_deps.pth` file.

So the solution is probably either to modify `virtualenv_create` to be idempotent or to replace the `virtualenv_install_with_resources` call with `venv.pip_install resources` and `venv.pip_install_and_link buildpath`.

**Comment by mistydemeo** [comment]
Got it! In that case, yeah, it looks like this behaviour is actually intentional(ish), at least in that we don't want to be able to `Pathname#write` to something that already exists: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/pathname.rb#L176

We're writing the `homebrew_deps.pth` here: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/python.rb#L148

The problem here I think is that we first explicitly call `virtualenv_create(libexec, "python3")`, then later on we call `virtualenv_install_with_resources`, which itself calls `virtualenv_create`. That will result in a duplicate call to writing `homebrew_deps.pth`.

**Comment by danielnachun** [comment]
I think I understand now too.  I guess the issue is that this formula needs `wheel` and `cffi` to be installed in the virtualenv before installing the other resources, and then we still use `virtualenv_install_with_resources` afterward to install the other resources, because it would be a pain to call `venv.pip_install` for all the others.

I can confirm that replacing `virtualenv_install_with_resource` with `venv.pip_install resources` and `venv.pip_install_and_link buildpath` allows this formula to build with no issues.  I will open a PR to fix this formula in homebrew-core.  I'll also open an issue homebrew/brew to see if we can figure out some way for `virtualenv_install_with_resources` to better handle the scenario encountered here where a virtualenv already exists.

**Comment by Rylan12** [comment]
Yes, I can confirm that they are listed separately for that reason.

I'd still like to know why this only fails on Linux but I'm too tired to look into that now (plus I don't have a Linux machine to test on). Since the `homebrew_deps.pth` file seems to only be written on Linux, it seems that one of the linux-only dependencies must have a `site-packages` directory (or a dependency only has this directory on Linux). `libffi` and `pkg-config` are the two linux-only dependencies. `pkg-config` should be skipped because it's a build-only dependency. `libffi` doesn't seem to need this directory, though, so I'm not really sure what to make of this.

**Comment by danielnachun** [comment]
If you want to test locally in our Docker CI env on your Mac, you can use `docker run -it homebrew/ubuntu16.04:master` to get the Linux environment we build in.  I use this all the time and it's a huge help for debugging!

I'm inclined to blame some weird interaction between the `cffi` resource and `libffi` for this, though as you've noted it does not have a `site-packages` directory (it's a C-only library) so it's quite odd.  I'll see if we can dig deeper into this when I open the issue in hombrew/brew tomorrow as it would be good to root out what's really going on here.  Thanks @Rylan12  and @mistydemeo for your help with this!

**Comment by mistydemeo** [comment]
This feels like a good argument in favour of switching to a `write` method that allows file clobbering. In this context, it seems likely safe to reinitialize the virtualenv.

Hypothesis: we're seeing different behaviour between Mac and Linux because `virtualenv_create(libexec, "python3")` is using the macOS-provided system Python 3 on macOS, but ends up pulling in the Homebrew Python 3 on Linux. Thus, the two virtualenvs are (usually) writing into different paths on macOS but the same path on Linux.

**Comment by Bo98** [comment]
> `virtualenv_create(libexec, "python3")` is using the macOS-provided system Python 3 on macOS

`python@3.9` is a dependency and dependencies should have priority in the `PATH`.

In fact, on Mojave it has to be using brewed Python as a system Python 3 doesn't exist.

**Comment by robolange** [comment]
When someone gets a moment, what's the status on this? I think @danielnachun mentioned opening a PR in homebrew-core. Did that ever happen?

**Comment by danielnachun** [comment]
The fix was merged in homebrew/core, so once it's merged here it should be bottled and will be ready to go.

**Comment by robolange** [comment]
I just updated and was able to install magic-wormhole on Linux. Thanks all.
