### ISSUE TITLE
Can not upgrade ansible => 3.3.0

### ISSUE THREAD

**Issue by dolgovas** [Homebrew/linuxbrew-core#23190]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 3.1.5-93-g5bd3fba
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5bd3fbad27d98ca8dec80446802522f544cbbeed
Last commit: 15 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 00686c06dedec4ffb4e442432fa5956b6ed807f2
Core tap last commit: 19 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.72-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Ubuntu 20.04.2 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: 5.5.0_6
xorg: N/A
```
```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18
```
```


### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew update ansible...
fail
brew remove ansible
removed 3.2.0
brew install ansible...
still failed

### What happened (include all command output)?

```
```
==> /home/linuxbrew/.linuxbrew/Cellar/ansible/3.3.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/ansible--PyNaCl-20210506-
Last 15 lines from /home/meonacist/.cache/Homebrew/Logs/ansible/67.pip:
  ERROR: Failed building wheel for PyNaCl
Failed to build PyNaCl
ERROR: Could not build wheels for PyNaCl which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/ansible/3.3.0/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/ansible/3.3.0/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/ansible/3.3.0/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 358, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for PyNaCl which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the '/home/linuxbrew/.linuxbrew/Cellar/ansible/3.3.0/libexec/bin/python3.9 -m pip install --upgrade pip' command.
Removed build tracker: '/tmp/pip-req-tracker-dl_c1kb0'

READ THIS: https://docs.brew.sh/Troubleshooting

```

### What did you expect to happen?

`I wait for correct install ansible 3.3.0`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
win 10
wsl2
ubuntu 20.04.2
brew install ansible
```

**Comment by dolgovas** [comment]
Try to do this
```
comment Manually update package and run brew update-python-resources ansible
==> Retrieving PyPI dependencies for "ansible==3.3.0 apache-libcloud boto3 dnspython docker-py junos-eznc jxmlease kerberos ntc-templates openshift passlib
==> Excluding "ansible==3.3.0"
==> Getting PyPI info for "ansible-base==2.10.9"
==> Getting PyPI info for "apache-libcloud==3.3.1"
==> Getting PyPI info for "appdirs==1.4.4"
==> Getting PyPI info for "attrs==21.1.0"
==> Getting PyPI info for "bcrypt==3.2.0"
==> Getting PyPI info for "boto3==1.17.67"
==> Getting PyPI info for "botocore==1.20.67"
==> Getting PyPI info for "cachetools==4.2.2"
==> Getting PyPI info for "certifi==2020.12.5"
==> Getting PyPI info for "cffi==1.14.5"
==> Getting PyPI info for "chardet==4.0.0"
==> Getting PyPI info for "cliff==3.7.0"
==> Getting PyPI info for "cmd2==1.5.0"
==> Getting PyPI info for "colorama==0.4.4"
==> Getting PyPI info for "cryptography==3.4.7"
==> Getting PyPI info for "debtcollector==2.2.0"
==> Getting PyPI info for "decorator==5.0.7"
==> Getting PyPI info for "dnspython==2.1.0"
==> Getting PyPI info for "docker-py==1.10.6"
==> Getting PyPI info for "docker-pycreds==0.4.0"
==> Getting PyPI info for "dogpile-cache==1.1.2"
==> Getting PyPI info for "future==0.18.2"
==> Getting PyPI info for "google-auth==1.30.0"
==> Getting PyPI info for "idna==2.10"
==> Getting PyPI info for "iso8601==0.1.14"
==> Getting PyPI info for "jinja2==2.11.3"
==> Getting PyPI info for "jmespath==0.10.0"
==> Getting PyPI info for "jsonpatch==1.32"
==> Getting PyPI info for "jsonpointer==2.1"
==> Getting PyPI info for "junos-eznc==2.6.0"
==> Getting PyPI info for "jxmlease==1.0.3"
==> Getting PyPI info for "kerberos==1.3.1"
==> Getting PyPI info for "keystoneauth1==4.3.1"
==> Getting PyPI info for "kubernetes==12.0.1"
==> Getting PyPI info for "lxml==4.6.3"
==> Getting PyPI info for "markupsafe==1.1.1"
==> Getting PyPI info for "msgpack==1.0.2"
==> Getting PyPI info for "munch==2.5.0"
==> Getting PyPI info for "ncclient==0.6.9"
==> Getting PyPI info for "netaddr==0.8.0"
==> Getting PyPI info for "netifaces==0.10.9"
==> Getting PyPI info for "ntc-templates==2.0.0"
==> Getting PyPI info for "ntlm-auth==1.5.0"
==> Getting PyPI info for "oauthlib==3.1.0"
==> Getting PyPI info for "openshift==0.12.0"
==> Getting PyPI info for "openstacksdk==0.56.0"
==> Getting PyPI info for "os-client-config==2.1.0"
==> Getting PyPI info for "os-service-types==1.7.0"
==> Getting PyPI info for "osc-lib==2.3.1"
==> Getting PyPI info for "oslo-config==8.6.0"
==> Getting PyPI info for "oslo-context==3.2.0"
==> Getting PyPI info for "oslo-i18n==5.0.1"
==> Getting PyPI info for "oslo-log==4.4.0"
==> Getting PyPI info for "oslo-serialization==4.1.0"
==> Getting PyPI info for "oslo-utils==4.8.0"
==> Getting PyPI info for "packaging==20.9"
==> Getting PyPI info for "paramiko==2.7.2"
==> Getting PyPI info for "passlib==1.7.4"
==> Getting PyPI info for "pbr==5.6.0"
==> Getting PyPI info for "pexpect==4.8.0"
==> Getting PyPI info for "prettytable==2.1.0"
==> Getting PyPI info for "ptyprocess==0.7.0"
==> Getting PyPI info for "pyasn1==0.4.8"
==> Getting PyPI info for "pyasn1-modules==0.2.8"
==> Getting PyPI info for "pycparser==2.20"
==> Excluding "pycrypto==2.6.1"
==> Getting PyPI info for "pyinotify==0.9.6"
==> Getting PyPI info for "pynacl==1.4.0"
==> Getting PyPI info for "pyopenssl==20.0.1"
==> Getting PyPI info for "pyparsing==2.4.7"
==> Getting PyPI info for "pyperclip==1.8.2"
==> Getting PyPI info for "pyserial==3.5"
==> Getting PyPI info for "pysphere3==0.1.8"
==> Getting PyPI info for "pyspnego==0.1.5"
==> Getting PyPI info for "python-consul==1.1.0"
==> Getting PyPI info for "python-dateutil==2.8.1"
==> Getting PyPI info for "python-keyczar==0.716"
==> Getting PyPI info for "python-keystoneclient==4.2.0"
==> Getting PyPI info for "python-neutronclient==7.3.0"
==> Getting PyPI info for "python-string-utils==1.0.0"
==> Getting PyPI info for "pytz==2021.1"
==> Getting PyPI info for "pywinrm==0.4.1"
==> Getting PyPI info for "pyyaml==5.4.1"
==> Getting PyPI info for "requests==2.25.1"
==> Getting PyPI info for "requests-credssp==1.2.0"
==> Getting PyPI info for "requests-ntlm==1.1.0"
==> Getting PyPI info for "requests-oauthlib==1.3.0"
==> Getting PyPI info for "requestsexceptions==1.4.0"
==> Getting PyPI info for "rfc3986==1.4.0"
==> Getting PyPI info for "rsa==4.7.2"
==> Getting PyPI info for "ruamel-yaml==0.17.4"
==> Getting PyPI info for "ruamel-yaml-clib==0.2.2"
==> Getting PyPI info for "s3transfer==0.4.2"
==> Getting PyPI info for "scp==0.13.3"
==> Excluding "setuptools==56.1.0"
==> Getting PyPI info for "shade==1.33.0"
==> Getting PyPI info for "simplejson==3.17.2"
==> Getting PyPI info for "six==1.16.0"
==> Getting PyPI info for "stevedore==3.3.0"
==> Excluding "textfsm==1.1.0"
==> Getting PyPI info for "transitions==0.8.8"
==> Getting PyPI info for "urllib3==1.26.4"
==> Getting PyPI info for "wcwidth==0.2.5"
==> Getting PyPI info for "websocket-client==0.59.0"
==> Getting PyPI info for "wrapt==1.12.1"
==> Getting PyPI info for "xmltodict==0.12.0"
==> Getting PyPI info for "yamlordereddictloader==0.4.0"
==> Getting PyPI info for "zabbix-api==0.5.4"
==> Updating resource blocks
```
It doesn't take effect

**Comment by dolgovas** [comment]
Try run interactive mode and upgrade pip manually....but error is still with me

```
/home/linuxbrew/.linuxbrew/Cellar/ansible/3.3.0/libexec/bin/python3.9 -m pip install --upgrade pip
Requirement already satisfied: pip in /home/linuxbrew/.linuxbrew/Cellar/ansible/3.3.0/libexec/lib/python3.9/site-packages (21.1.1)
and manually run PyNaCl installation
```
```
  copying src/nacl/bindings/crypto_sign.py -> build/lib.linux-x86_64-3.9/nacl/bindings
  running build_clib
  Traceback (most recent call last):
    File "/home/linuxbrew/.linuxbrew/Cellar/ansible/3.3.0/libexec/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/home/linuxbrew/.linuxbrew/Cellar/ansible/3.3.0/libexec/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/linuxbrew/.linuxbrew/Cellar/ansible/3.3.0/libexec/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-h63rq1q5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-h63rq1q5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-h63rq1q5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 216, in <module>
      setup(
    File "/tmp/pip-build-env-h63rq1q5/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-h63rq1q5/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 161, in run
      raise Exception("ERROR: The 'make' utility is missing from PATH")
  Exception: ERROR: The 'make' utility is missing from PATH
  Building wheel for PyNaCl (PEP 517) ... error
  ERROR: Failed building wheel for PyNaCl
Failed to build PyNaCl
ERROR: Could not build wheels for PyNaCl which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/ansible/3.3.0/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/ansible/3.3.0/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/ansible/3.3.0/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 360, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for PyNaCl which use PEP 517 and cannot be installed directly
Removed build tracker: '/tmp/pip-req-tracker-yuhiv7en'
```

**Comment by dolgovas** [comment]
Hm.
I found solution, worked for me...
`apt install make -y`
than
`/home/linuxbrew/.linuxbrew/Cellar/ansible/3.3.0: 55,489 files, 536.9MB, built in 13 minutes 22 seconds`
before that. I don't need to install make from apt...
If this solution is - ok. Issue may closed =)

**Comment by danielnachun** [comment]
The PEP517 error started showing up when the Python cryptography library started requiring Rust as a dependency.  I see that it has already been added, so I guess perhaps you were missing `make`.  Also this formula should be bottled as everything works fine in CI, so I've requested a new bottle.

**Comment by danielnachun** [comment]
`ansible` is rebottled now and as a relocatable bottle, should not need to be built from source for any users.
