### ISSUE TITLE
Unable to install awscli 2.2.4 using the Brew Docker image

### ISSUE THREAD

**Issue by vhalis** [Homebrew/linuxbrew-core#23244]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

`brew config`
```shell
HOMEBREW_VERSION: 3.1.7-42-gd45832b
ORIGIN: https://github.com/Homebrew/brew
HEAD: d45832bbfc7a7e89a7f54cc314c93a087decf89f
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 210133ee79ebab9b814d6b9d9063ee05d82e40b4
Core tap last commit: 17 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 12.0.0 build (parse error)
Git: 2.31.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-73-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.2 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

`brew doctor`
```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was attempting to upgrade my version of `awscli` from 2.0.3 to 2.2.4, and the newer version failed to install. This occurred first on my local machine but was also reproducible using the Docker image.

### What happened (include all command output)?

I've excluded the many dependencies that were installed successfully by running this command.
```shell
==> Installing awscli
==> python3 -m venv /home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.4/libexec
==> /home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.4/libexec/bin/pip install -v -r requirements.txt --ignore-installed /tmp/awscli-20210515-12287-qdu4lb/aws-cli-2.2.4
Last 15 lines from /root/.cache/Homebrew/Logs/awscli/02.pip:
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=ExplicitRequirement(LinkCandidate('https://github.com/boto/botocore/zipball/v2#egg=botocore')), parent=None), RequirementInformation(requirement=SpecifierRequirement('botocore==2.0.0dev112'), parent=LinkCandidate('file:///tmp/awscli-20210515-12287-qdu4lb/aws-cli-2.2.4'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.4/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.4/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.4/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.4/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 136, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Removed build tracker: '/tmp/pip-req-tracker-pmalmxrk'
```

### What did you expect to happen?

The latest version of `awscli` should be installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
docker run --rm -it homebrew/brew
export HOMEBREW_DEVELOPER=1
brew install awscli
```

**Comment by vhalis** [comment]
Looks like version `2.2.5` installs just fine. Closing. :smile:
