### ISSUE TITLE
Pip resolution error installing awscli

### ISSUE THREAD

**Issue by Alexndrrr** [Homebrew/linuxbrew-core#23564]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
>>> brew config
HOMEBREW_VERSION: 3.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 33e71c99dc40c0a134a236fffe2594ae6572d83c
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 3f252ff5dd7019438c55889cb6fd1eca95c794f6
Core tap last commit: 82 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :100
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dual-core 64-bit skylake
Clang: 12.0.0 build (parse error)
Git: 2.23.4 => /bin/git
Curl: 7.61.1 => /usr/bin/curl
Kernel: Linux 4.14.232-176.381.amzn2.x86_64 x86_64 GNU/Linux
OS: Amazon Linux release 2 (Karoo) (Karoo)
Host glibc: 2.26
/usr/bin/gcc: 7.3.1
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A



>>> brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install awscli

### What happened (include all command output)?

```sh
>>> brew install awscli
==> Downloading https://github.com/aws/aws-cli/archive/2.2.12.tar.gz
Already downloaded: /home/[...]/.cache/Homebrew/downloads/2f1e8a5cdba513b34e3dce3837c74187367e15a76a8480d7276869af47f43d64--aws-cli-2.2.12.tar.gz
==> python3 -m venv /home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.12/libexec
==> /home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.12/libexec/bin/pip install -v -r requirements.txt --ignore-installed /tmp/awscli-20210618-5885-dlnh0v/aws-cli-2.2.12
Last 15 lines from /home/[...]/.cache/Homebrew/Logs/awscli/02.pip:
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.12/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.12/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.12/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.12/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 136, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.12/libexec/bin/python3.9 -m pip install --upgrade pip' command.
Removed build tracker: '/tmp/pip-req-tracker-3mtd1y60'

READ THIS: https://docs.brew.sh/Troubleshooting
```

### What did you expect to happen?

Awscli to install sucessfully

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install awscli
```

**Comment by abstratt** [comment]
@Alexndrrr Have you found any workaround here?

**Comment by brl0** [comment]
This probably relates to #23867, which is the error I am currently seeing.  Since that issue is the result of installing the same package as in this issue, I am guessing this issue may be obsolete and might ought to be closed.

**Comment by 4ndr4s** [comment]
@brl0 @abstratt you guys can find a better output if you use brew install --verbose awscli, something similar to:

```
Collecting urllib3<1.27,>=1.25.4
  Created temporary directory: /tmp/pip-unpack-bpam87zl
  Looking up "https://files.pythonhosted.org/packages/5f/64/43575537846896abac0b15c3e5ac678d787a4021e906703f1766bfb8ea11/urllib3-1.26.6-py2.py3-none-any.whl" in the cache
  No cache entry available
  https://files.pythonhosted.org:443 "GET /packages/5f/64/43575537846896abac0b15c3e5ac678d787a4021e906703f1766bfb8ea11/urllib3-1.26.6-py2.py3-none-any.whl HTTP/1.1" 200 138494
  Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
  Ignoring unknown cache-control directive: immutable
  Updating cache with response from "https://files.pythonhosted.org/packages/5f/64/43575537846896abac0b15c3e5ac678d787a4021e906703f1766bfb8ea11/urllib3-1.26.6-py2.py3-none-any.whl"
  Caching due to etag
  Added urllib3<1.27,>=1.25.4 from https://files.pythonhosted.org/packages/5f/64/43575537846896abac0b15c3e5ac678d787a4021e906703f1766bfb8ea11/urllib3-1.26.6-py2.py3-none-any.whl#sha256=39fb8672126159acb139a7718dd10806104dec1e2f0f6c88aab05d17df10c8d4 (from botocore->-r requirements.txt (line 6)) to build tracker '/tmp/pip-req-tracker-8ytktsst'
  Removed urllib3<1.27,>=1.25.4 from https://files.pythonhosted.org/packages/5f/64/43575537846896abac0b15c3e5ac678d787a4021e906703f1766bfb8ea11/urllib3-1.26.6-py2.py3-none-any.whl#sha256=39fb8672126159acb139a7718dd10806104dec1e2f0f6c88aab05d17df10c8d4 (from botocore->-r requirements.txt (line 6)) from build tracker '/tmp/pip-req-tracker-8ytktsst'
INFO: pip is looking at multiple versions of botocore to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install awscli==2.2.19 and botocore 2.0.0.dev128 (from https://github.com/boto/botocore/zipball/v2#egg=botocore) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested botocore 2.0.0.dev128 (from https://github.com/boto/botocore/zipball/v2#egg=botocore)
    awscli 2.2.19 depends on botocore==2.0.0dev127

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Exception information:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.19/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    result = self._result = resolver.resolve(
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.19/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.19/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 377, in resolve
    raise ResolutionImpossible(causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=ExplicitRequirement(LinkCandidate('https://github.com/boto/botocore/zipball/v2#egg=botocore')), parent=None), RequirementInformation(requirement=SpecifierRequirement('botocore==2.0.0dev127'), parent=LinkCandidate('file:///tmp/awscli-20210719-5908-zvmc1x/aws-cli-2.2.19'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.19/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.19/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.19/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.19/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 136, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Removed build tracker: '/tmp/pip-req-tracker-8ytktsst'
ln -s ../../Cellar/awscli/2.2.16/etc/bash_completion.d/aws_bash_completer aws_bash_completer
ln -s ../Cellar/awscli/2.2.16/bin/aws aws
ln -s ../Cellar/awscli/2.2.16/bin/aws_completer aws_completer
ln -s ../Cellar/awscli/2.2.16/bin/aws_legacy_completer aws_legacy_completer
ln -s ../Cellar/awscli/2.2.16/share/awscli awscli
ln -s ../../../Cellar/awscli/2.2.16/share/zsh/site-functions/_aws _aws
ln -s ../../../Cellar/awscli/2.2.16/share/zsh/site-functions/aws_zsh_completer.sh aws_zsh_completer.sh

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/awscli.rb
==> Configuration
HOMEBREW_VERSION: 3.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 16b01d6e019e93b66e41d0bb8da66fec3fcc5cca
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: c48a5fa6425ca6398842a189ad1718d7b0454776
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 12.0.1 build (parse error)
Git: 2.32.0 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.10.25-linuxkit x86_64 GNU/Linux
OS: Ubuntu 20.04.2 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
==> ENV
HOMEBREW_CC: gcc-11
HOMEBREW_CXX: g++-11
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /home/linuxbrew/.linuxbrew
PKG_CONFIG_PATH: /home/linuxbrew/.linuxbrew/opt/openssl@1.1/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/ncurses/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/readline/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/zlib/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/sqlite/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/xz/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/expat/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libffi/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libpng/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/freetype/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxml2/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/util-linux/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/fontconfig/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/jbig2dec/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/jpeg/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libidn/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libtiff/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/little-cms2/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/openjpeg/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/gmp/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/isl/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/mpfr/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/zstd/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libpthread-stubs/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxau/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxdmcp/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxcb/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libx11/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxext/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxfixes/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxi/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxrender/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxrandr/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxxf86vm/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxdamage/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libedit/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libelf/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxshmfence/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxv/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxvmc/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libpciaccess/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libdrm/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/wayland/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libva/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libvdpau/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/mesa/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/mesa-glu/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxinerama/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/freeglut/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/jasper/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/netpbm/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/uchardet/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/pcre/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/glib/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libyaml/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/xorgproto/share/pkgconfig:/home/linuxbrew/.linuxbrew/opt/wayland-protocols/share/pkgconfig
HOMEBREW_GIT: git
ACLOCAL_PATH: /home/linuxbrew/.linuxbrew/share/aclocal
PATH: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super:/home/linuxbrew/.linuxbrew/opt/cmake/bin:/home/linuxbrew/.linuxbrew/opt/gdbm/bin:/home/linuxbrew/.linuxbrew/opt/openssl@1.1/bin:/home/linuxbrew/.linuxbrew/opt/ncurses/bin:/home/linuxbrew/.linuxbrew/opt/sqlite/bin:/home/linuxbrew/.linuxbrew/opt/xz/bin:/home/linuxbrew/.linuxbrew/opt/bzip2/bin:/home/linuxbrew/.linuxbrew/opt/expat/bin:/home/linuxbrew/.linuxbrew/opt/unzip/bin:/home/linuxbrew/.linuxbrew/opt/python@3.9/bin:/home/linuxbrew/.linuxbrew/opt/libpng/bin:/home/linuxbrew/.linuxbrew/opt/freetype/bin:/home/linuxbrew/.linuxbrew/opt/libxml2/bin:/home/linuxbrew/.linuxbrew/opt/gettext/bin:/home/linuxbrew/.linuxbrew/opt/util-linux/bin:/home/linuxbrew/.linuxbrew/opt/fontconfig/bin:/home/linuxbrew/.linuxbrew/opt/jbig2dec/bin:/home/linuxbrew/.linuxbrew/opt/jpeg/bin:/home/linuxbrew/.linuxbrew/opt/libidn/bin:/home/linuxbrew/.linuxbrew/opt/libtiff/bin:/home/linuxbrew/.linuxbrew/opt/little-cms2/bin:/home/linuxbrew/.linuxbrew/opt/openjpeg/bin:/home/linuxbrew/.linuxbrew/opt/zstd/bin:/home/linuxbrew/.linuxbrew/opt/binutils/bin:/home/linuxbrew/.linuxbrew/opt/gcc/bin:/home/linuxbrew/.linuxbrew/opt/ghostscript/bin:/home/linuxbrew/.linuxbrew/opt/pkg-config/bin:/home/linuxbrew/.linuxbrew/opt/llvm/bin:/home/linuxbrew/.linuxbrew/opt/lm-sensors/bin:/home/linuxbrew/.linuxbrew/opt/wayland/bin:/home/linuxbrew/.linuxbrew/opt/mesa/bin:/home/linuxbrew/.linuxbrew/opt/xinput/bin:/home/linuxbrew/.linuxbrew/opt/jasper/bin:/home/linuxbrew/.linuxbrew/opt/netpbm/bin:/home/linuxbrew/.linuxbrew/opt/psutils/bin:/home/linuxbrew/.linuxbrew/opt/uchardet/bin:/home/linuxbrew/.linuxbrew/opt/berkeley-db/bin:/home/linuxbrew/.linuxbrew/opt/perl/bin:/home/linuxbrew/.linuxbrew/opt/pcre/bin:/home/linuxbrew/.linuxbrew/opt/glib/bin:/home/linuxbrew/.linuxbrew/opt/groff/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: awscli 2.2.19 did not build
Logs:
     /root/.cache/Homebrew/Logs/awscli/02.pip
     /root/.cache/Homebrew/Logs/awscli/02.pip.cc
     /root/.cache/Homebrew/Logs/awscli/01.python3
     /root/.cache/Homebrew/Logs/awscli/00.options.out
READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
awscli dependencies conflicts https://github.com/Homebrew/linuxbrew-core/issues/23867
Pip resolution error installing awscli https://github.com/Homebrew/linuxbrew-core/issues/23564
```

@brl0, could be not related with your error I was able to install awscli (2.2.16) two weeks ago without any issue.

**Comment by brl0** [comment]
@4ndr4s, Thanks for the information.  
I too have been able to install awscli until recently.  My thought was that this particular issue may have been fixed since it was originally posted, before the issue that you posted arose sometime in the last couple of days.  I figured posting a comment may help prompt cleaning up this potentially obsolete issue if that is indeed the case.

**Comment by iMichka** [comment]
We have an awscli bottle now so this should be fixed.
