### ISSUE TITLE
awscli dependencies conflicts

### ISSUE THREAD

**Issue by 4ndr4s** [Homebrew/linuxbrew-core#23867]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
linuxbrew@8f7eef5b6b71:/home/linuxbrew# brew config
HOMEBREW_VERSION: 3.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 16b01d6e019e93b66e41d0bb8da66fec3fcc5cca
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: ef5cce4a5414abee2fd10472461b3954c47e9e98
Core tap last commit: 5 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 12.0.1 build (parse error)
Git: 2.32.0 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.10.25-linuxkit x86_64 GNU/Linux
OS: Ubuntu 20.04.2 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
linuxbrew@8f7eef5b6b71:/home/linuxbrew# brew doctor
Your system is ready to brew.
linuxbrew@8f7eef5b6b71:/home/linuxbrew#
```
```


### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to install awscli on a linux docker, but is failing because dependencies conflicts.

```
ERROR: Cannot install awscli==2.2.19 and botocore 2.0.0.dev128 (from https://github.com/boto/botocore/zipball/v2#egg=botocore) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested botocore 2.0.0.dev128 (from https://github.com/boto/botocore/zipball/v2#egg=botocore)
    awscli 2.2.19 depends on botocore==2.0.0dev127
```



### What happened (include all command output)?

linuxbrew@8f7eef5b6b71:/home/linuxbrew# brew --version
Homebrew 3.2.3
Homebrew/homebrew-core (git revision ef5cce4a541; last commit 2021-07-19)
linuxbrew@8f7eef5b6b71:/home/linuxbrew# brew install  awscli
==> Downloading https://github.com/aws/aws-cli/archive/2.2.19.tar.gz
Already downloaded: /root/.cache/Homebrew/downloads/12a73374f32a904dc52860225030876862fc8ece229b1767ee73cb856af1f6ba--aws-cli-2.2.19.tar.gz
==> python3 -m venv --system-site-packages /home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.19/libexec
==> /home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.19/libexec/bin/pip install -v -r requirements.txt --ignore-installed /tmp/awscli-20210719-82161-1p5mifj/aws-cli-2.2.19
Last 15 lines from /root/.cache/Homebrew/Logs/awscli/02.pip:
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=ExplicitRequirement(LinkCandidate('https://github.com/boto/botocore/zipball/v2#egg=botocore')), parent=None), RequirementInformation(requirement=SpecifierRequirement('botocore==2.0.0dev127'), parent=LinkCandidate('file:///tmp/awscli-20210719-82161-1p5mifj/aws-cli-2.2.19'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.19/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.19/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.19/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.19/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 136, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Removed build tracker: '/tmp/pip-req-tracker-r06vy1sy'

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
Pip resolution error installing awscli https://github.com/Homebrew/linuxbrew-core/issues/23564

### What did you expect to happen?

Get the awscli installation successful 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
run a linux docker container.

install brew 

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

optionally you can run brew update, didn't take any effect in my case.

run: 

brew tap aws/tap
brew install awscli
```

**Comment by iMichka** [comment]
The latests versions of `awscli` have been bottled; so this does not seem to be an issue anymore.
